<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events/ResolutionRouteInfo.proto

namespace GPBMetadata\Events;

class ResolutionRouteInfo
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
Ä
 Events/ResolutionRouteInfo.protoDiadoc.Api.Proto.Events"@
ResolutionRouteAssignmentInfo
RouteId (	
Author (	"=
ResolutionRouteRemovalInfo
RouteId (	
Author (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

