<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Documents/DetectTitleResponse.proto

namespace Diadoc\Api\Proto\Documents;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Documents.DetectTitleResponse</code>
 */
class DetectTitleResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Documents.DetectedDocumentTitle DocumentTitles = 1;</code>
     */
    private $DocumentTitles;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Diadoc\Api\Proto\Documents\DetectedDocumentTitle>|\Google\Protobuf\Internal\RepeatedField $DocumentTitles
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Documents\DetectTitleResponse::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Documents.DetectedDocumentTitle DocumentTitles = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDocumentTitles()
    {
        return $this->DocumentTitles;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Documents.DetectedDocumentTitle DocumentTitles = 1;</code>
     * @param array<\Diadoc\Api\Proto\Documents\DetectedDocumentTitle>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDocumentTitles($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Documents\DetectedDocumentTitle::class);
        $this->DocumentTitles = $arr;

        return $this;
    }

}

