<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CounteragentGroups/DepartmentsInGroup.proto

namespace GPBMetadata\CounteragentGroups;

class DepartmentsInGroup
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
‡
+CounteragentGroups/DepartmentsInGroup.proto#Diadoc.Api.Proto.CounteragentGroups"+
DepartmentsInGroup
DepartmentIds (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

