<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Users/UserToUpdate.proto

namespace Diadoc\Api\Proto\Users;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Users.UserLoginPatch</code>
 */
class UserLoginPatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Login = 1;</code>
     */
    protected $Login = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Login
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Users\UserToUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Login = 1;</code>
     * @return string
     */
    public function getLogin()
    {
        return isset($this->Login) ? $this->Login : '';
    }

    public function hasLogin()
    {
        return isset($this->Login);
    }

    public function clearLogin()
    {
        unset($this->Login);
    }

    /**
     * Generated from protobuf field <code>optional string Login = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLogin($var)
    {
        GPBUtil::checkString($var, True);
        $this->Login = $var;

        return $this;
    }

}

