<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CustomPrintFormDetection.proto

namespace GPBMetadata;

class CustomPrintFormDetection
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\DocumentId::initOnce();
        $pool->internalAddGeneratedFile(
            '
ë
CustomPrintFormDetection.protoDiadoc.Api.Proto"T
CustomPrintFormDetectionRequest1
DocumentIds (2.Diadoc.Api.Proto.DocumentId"e
CustomPrintFormDetectionResultC
Items (24.Diadoc.Api.Proto.CustomPrintFormDetectionItemResult"r
"CustomPrintFormDetectionItemResult0

DocumentId (2.Diadoc.Api.Proto.DocumentId
HasCustomPrintForm (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

