<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: FullVersion.proto

namespace GPBMetadata;

class FullVersion
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
t
FullVersion.protoDiadoc.Api.Proto"E
FullVersion
TypeNamedId (	
Function (	
Version (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

