<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ResolutionRouteList.proto

namespace GPBMetadata;

class ResolutionRouteList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
»
ResolutionRouteList.protoDiadoc.Api.Proto"R
ResolutionRouteList;
ResolutionRoutes (2!.Diadoc.Api.Proto.ResolutionRoute"0
ResolutionRoute
RouteId (	
Name (	bproto3'
        , true);

        static::$is_initialized = true;
    }
}

