<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events/DiadocCounteragent-GetApi.proto

namespace Diadoc\Api\Proto\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Events.CounteragentInfo</code>
 */
class CounteragentInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string CounteragentBoxId = 1;</code>
     */
    protected $CounteragentBoxId = '';
    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.CounteragentStatus Status = 2;</code>
     */
    protected $Status = 0;
    /**
     * Generated from protobuf field <code>sfixed64 EventTimestampTicks = 3;</code>
     */
    protected $EventTimestampTicks = 0;
    /**
     * Generated from protobuf field <code>optional string LastEventComment = 4;</code>
     */
    protected $LastEventComment = null;
    /**
     * Generated from protobuf field <code>optional string MessageFromCounteragent = 5;</code>
     */
    protected $MessageFromCounteragent = null;
    /**
     * Generated from protobuf field <code>optional string MessageToCounteragent = 6;</code>
     */
    protected $MessageToCounteragent = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId InvitationDocumentId = 7;</code>
     */
    protected $InvitationDocumentId = null;
    /**
     * Generated from protobuf field <code>optional string CounteragentGroupId = 8;</code>
     */
    protected $CounteragentGroupId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $CounteragentBoxId
     *     @type int $Status
     *     @type int|string $EventTimestampTicks
     *     @type string $LastEventComment
     *     @type string $MessageFromCounteragent
     *     @type string $MessageToCounteragent
     *     @type \Diadoc\Api\Proto\DocumentId $InvitationDocumentId
     *     @type string $CounteragentGroupId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events\DiadocCounteragentGetApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string CounteragentBoxId = 1;</code>
     * @return string
     */
    public function getCounteragentBoxId()
    {
        return $this->CounteragentBoxId;
    }

    /**
     * Generated from protobuf field <code>string CounteragentBoxId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCounteragentBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CounteragentBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.CounteragentStatus Status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.CounteragentStatus Status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\CounteragentStatus::class);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed64 EventTimestampTicks = 3;</code>
     * @return int|string
     */
    public function getEventTimestampTicks()
    {
        return $this->EventTimestampTicks;
    }

    /**
     * Generated from protobuf field <code>sfixed64 EventTimestampTicks = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setEventTimestampTicks($var)
    {
        GPBUtil::checkInt64($var);
        $this->EventTimestampTicks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string LastEventComment = 4;</code>
     * @return string
     */
    public function getLastEventComment()
    {
        return isset($this->LastEventComment) ? $this->LastEventComment : '';
    }

    public function hasLastEventComment()
    {
        return isset($this->LastEventComment);
    }

    public function clearLastEventComment()
    {
        unset($this->LastEventComment);
    }

    /**
     * Generated from protobuf field <code>optional string LastEventComment = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLastEventComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->LastEventComment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string MessageFromCounteragent = 5;</code>
     * @return string
     */
    public function getMessageFromCounteragent()
    {
        return isset($this->MessageFromCounteragent) ? $this->MessageFromCounteragent : '';
    }

    public function hasMessageFromCounteragent()
    {
        return isset($this->MessageFromCounteragent);
    }

    public function clearMessageFromCounteragent()
    {
        unset($this->MessageFromCounteragent);
    }

    /**
     * Generated from protobuf field <code>optional string MessageFromCounteragent = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageFromCounteragent($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageFromCounteragent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string MessageToCounteragent = 6;</code>
     * @return string
     */
    public function getMessageToCounteragent()
    {
        return isset($this->MessageToCounteragent) ? $this->MessageToCounteragent : '';
    }

    public function hasMessageToCounteragent()
    {
        return isset($this->MessageToCounteragent);
    }

    public function clearMessageToCounteragent()
    {
        unset($this->MessageToCounteragent);
    }

    /**
     * Generated from protobuf field <code>optional string MessageToCounteragent = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageToCounteragent($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageToCounteragent = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId InvitationDocumentId = 7;</code>
     * @return \Diadoc\Api\Proto\DocumentId|null
     */
    public function getInvitationDocumentId()
    {
        return $this->InvitationDocumentId;
    }

    public function hasInvitationDocumentId()
    {
        return isset($this->InvitationDocumentId);
    }

    public function clearInvitationDocumentId()
    {
        unset($this->InvitationDocumentId);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId InvitationDocumentId = 7;</code>
     * @param \Diadoc\Api\Proto\DocumentId $var
     * @return $this
     */
    public function setInvitationDocumentId($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\DocumentId::class);
        $this->InvitationDocumentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string CounteragentGroupId = 8;</code>
     * @return string
     */
    public function getCounteragentGroupId()
    {
        return isset($this->CounteragentGroupId) ? $this->CounteragentGroupId : '';
    }

    public function hasCounteragentGroupId()
    {
        return isset($this->CounteragentGroupId);
    }

    public function clearCounteragentGroupId()
    {
        unset($this->CounteragentGroupId);
    }

    /**
     * Generated from protobuf field <code>optional string CounteragentGroupId = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setCounteragentGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CounteragentGroupId = $var;

        return $this;
    }

}

