<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events/DiadocMessage-GetApi.proto

namespace Diadoc\Api\Proto\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Events.Message</code>
 */
class Message extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string MessageId = 1;</code>
     */
    protected $MessageId = '';
    /**
     * Generated from protobuf field <code>sfixed64 TimestampTicks = 2;</code>
     */
    protected $TimestampTicks = 0;
    /**
     * Generated from protobuf field <code>sfixed64 LastPatchTimestampTicks = 3;</code>
     */
    protected $LastPatchTimestampTicks = 0;
    /**
     * Generated from protobuf field <code>string FromBoxId = 4;</code>
     */
    protected $FromBoxId = '';
    /**
     * Generated from protobuf field <code>string FromTitle = 5;</code>
     */
    protected $FromTitle = '';
    /**
     * Generated from protobuf field <code>optional string ToBoxId = 6;</code>
     */
    protected $ToBoxId = null;
    /**
     * Generated from protobuf field <code>optional string ToTitle = 7;</code>
     */
    protected $ToTitle = null;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Events.Entity Entities = 8;</code>
     */
    private $Entities;
    /**
     * Generated from protobuf field <code>optional bool IsDraft = 9;</code>
     */
    protected $IsDraft = null;
    /**
     * Generated from protobuf field <code>optional bool DraftIsLocked = 10;</code>
     */
    protected $DraftIsLocked = null;
    /**
     * Generated from protobuf field <code>optional bool DraftIsRecycled = 11;</code>
     */
    protected $DraftIsRecycled = null;
    /**
     * Generated from protobuf field <code>optional string CreatedFromDraftId = 12;</code>
     */
    protected $CreatedFromDraftId = null;
    /**
     * Generated from protobuf field <code>repeated string DraftIsTransformedToMessageIdList = 13;</code>
     */
    private $DraftIsTransformedToMessageIdList;
    /**
     * Generated from protobuf field <code>optional bool IsDeleted = 14;</code>
     */
    protected $IsDeleted = null;
    /**
     * Generated from protobuf field <code>optional bool IsTest = 15;</code>
     */
    protected $IsTest = null;
    /**
     * Generated from protobuf field <code>optional bool IsInternal = 16;</code>
     */
    protected $IsInternal = null;
    /**
     * Generated from protobuf field <code>optional bool IsProxified = 17;</code>
     */
    protected $IsProxified = null;
    /**
     * Generated from protobuf field <code>optional string ProxyBoxId = 18;</code>
     */
    protected $ProxyBoxId = null;
    /**
     * Generated from protobuf field <code>optional string ProxyTitle = 19;</code>
     */
    protected $ProxyTitle = null;
    /**
     * Generated from protobuf field <code>optional bool PacketIsLocked = 20;</code>
     */
    protected $PacketIsLocked = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.LockMode LockMode = 21;</code>
     */
    protected $LockMode = 0;
    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Documents.MessageType MessageType = 22;</code>
     */
    protected $MessageType = 0;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Events.TemplateToLetterTransformationInfo TemplateToLetterTransformationInfo = 23;</code>
     */
    protected $TemplateToLetterTransformationInfo = null;
    /**
     * Generated from protobuf field <code>optional bool IsReusable = 24;</code>
     */
    protected $IsReusable = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $MessageId
     *     @type int|string $TimestampTicks
     *     @type int|string $LastPatchTimestampTicks
     *     @type string $FromBoxId
     *     @type string $FromTitle
     *     @type string $ToBoxId
     *     @type string $ToTitle
     *     @type array<\Diadoc\Api\Proto\Events\Entity>|\Google\Protobuf\Internal\RepeatedField $Entities
     *     @type bool $IsDraft
     *     @type bool $DraftIsLocked
     *     @type bool $DraftIsRecycled
     *     @type string $CreatedFromDraftId
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $DraftIsTransformedToMessageIdList
     *     @type bool $IsDeleted
     *     @type bool $IsTest
     *     @type bool $IsInternal
     *     @type bool $IsProxified
     *     @type string $ProxyBoxId
     *     @type string $ProxyTitle
     *     @type bool $PacketIsLocked
     *     @type int $LockMode
     *     @type int $MessageType
     *     @type \Diadoc\Api\Proto\Events\TemplateToLetterTransformationInfo $TemplateToLetterTransformationInfo
     *     @type bool $IsReusable
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events\DiadocMessageGetApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string MessageId = 1;</code>
     * @return string
     */
    public function getMessageId()
    {
        return $this->MessageId;
    }

    /**
     * Generated from protobuf field <code>string MessageId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed64 TimestampTicks = 2;</code>
     * @return int|string
     */
    public function getTimestampTicks()
    {
        return $this->TimestampTicks;
    }

    /**
     * Generated from protobuf field <code>sfixed64 TimestampTicks = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestampTicks($var)
    {
        GPBUtil::checkInt64($var);
        $this->TimestampTicks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>sfixed64 LastPatchTimestampTicks = 3;</code>
     * @return int|string
     */
    public function getLastPatchTimestampTicks()
    {
        return $this->LastPatchTimestampTicks;
    }

    /**
     * Generated from protobuf field <code>sfixed64 LastPatchTimestampTicks = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setLastPatchTimestampTicks($var)
    {
        GPBUtil::checkInt64($var);
        $this->LastPatchTimestampTicks = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FromBoxId = 4;</code>
     * @return string
     */
    public function getFromBoxId()
    {
        return $this->FromBoxId;
    }

    /**
     * Generated from protobuf field <code>string FromBoxId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setFromBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FromBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string FromTitle = 5;</code>
     * @return string
     */
    public function getFromTitle()
    {
        return $this->FromTitle;
    }

    /**
     * Generated from protobuf field <code>string FromTitle = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setFromTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->FromTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ToBoxId = 6;</code>
     * @return string
     */
    public function getToBoxId()
    {
        return isset($this->ToBoxId) ? $this->ToBoxId : '';
    }

    public function hasToBoxId()
    {
        return isset($this->ToBoxId);
    }

    public function clearToBoxId()
    {
        unset($this->ToBoxId);
    }

    /**
     * Generated from protobuf field <code>optional string ToBoxId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setToBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ToTitle = 7;</code>
     * @return string
     */
    public function getToTitle()
    {
        return isset($this->ToTitle) ? $this->ToTitle : '';
    }

    public function hasToTitle()
    {
        return isset($this->ToTitle);
    }

    public function clearToTitle()
    {
        unset($this->ToTitle);
    }

    /**
     * Generated from protobuf field <code>optional string ToTitle = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setToTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Events.Entity Entities = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getEntities()
    {
        return $this->Entities;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Events.Entity Entities = 8;</code>
     * @param array<\Diadoc\Api\Proto\Events\Entity>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setEntities($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Events\Entity::class);
        $this->Entities = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsDraft = 9;</code>
     * @return bool
     */
    public function getIsDraft()
    {
        return isset($this->IsDraft) ? $this->IsDraft : false;
    }

    public function hasIsDraft()
    {
        return isset($this->IsDraft);
    }

    public function clearIsDraft()
    {
        unset($this->IsDraft);
    }

    /**
     * Generated from protobuf field <code>optional bool IsDraft = 9;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDraft($var)
    {
        GPBUtil::checkBool($var);
        $this->IsDraft = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool DraftIsLocked = 10;</code>
     * @return bool
     */
    public function getDraftIsLocked()
    {
        return isset($this->DraftIsLocked) ? $this->DraftIsLocked : false;
    }

    public function hasDraftIsLocked()
    {
        return isset($this->DraftIsLocked);
    }

    public function clearDraftIsLocked()
    {
        unset($this->DraftIsLocked);
    }

    /**
     * Generated from protobuf field <code>optional bool DraftIsLocked = 10;</code>
     * @param bool $var
     * @return $this
     */
    public function setDraftIsLocked($var)
    {
        GPBUtil::checkBool($var);
        $this->DraftIsLocked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool DraftIsRecycled = 11;</code>
     * @return bool
     */
    public function getDraftIsRecycled()
    {
        return isset($this->DraftIsRecycled) ? $this->DraftIsRecycled : false;
    }

    public function hasDraftIsRecycled()
    {
        return isset($this->DraftIsRecycled);
    }

    public function clearDraftIsRecycled()
    {
        unset($this->DraftIsRecycled);
    }

    /**
     * Generated from protobuf field <code>optional bool DraftIsRecycled = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setDraftIsRecycled($var)
    {
        GPBUtil::checkBool($var);
        $this->DraftIsRecycled = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string CreatedFromDraftId = 12;</code>
     * @return string
     */
    public function getCreatedFromDraftId()
    {
        return isset($this->CreatedFromDraftId) ? $this->CreatedFromDraftId : '';
    }

    public function hasCreatedFromDraftId()
    {
        return isset($this->CreatedFromDraftId);
    }

    public function clearCreatedFromDraftId()
    {
        unset($this->CreatedFromDraftId);
    }

    /**
     * Generated from protobuf field <code>optional string CreatedFromDraftId = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setCreatedFromDraftId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CreatedFromDraftId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string DraftIsTransformedToMessageIdList = 13;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDraftIsTransformedToMessageIdList()
    {
        return $this->DraftIsTransformedToMessageIdList;
    }

    /**
     * Generated from protobuf field <code>repeated string DraftIsTransformedToMessageIdList = 13;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDraftIsTransformedToMessageIdList($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->DraftIsTransformedToMessageIdList = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsDeleted = 14;</code>
     * @return bool
     */
    public function getIsDeleted()
    {
        return isset($this->IsDeleted) ? $this->IsDeleted : false;
    }

    public function hasIsDeleted()
    {
        return isset($this->IsDeleted);
    }

    public function clearIsDeleted()
    {
        unset($this->IsDeleted);
    }

    /**
     * Generated from protobuf field <code>optional bool IsDeleted = 14;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDeleted($var)
    {
        GPBUtil::checkBool($var);
        $this->IsDeleted = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsTest = 15;</code>
     * @return bool
     */
    public function getIsTest()
    {
        return isset($this->IsTest) ? $this->IsTest : false;
    }

    public function hasIsTest()
    {
        return isset($this->IsTest);
    }

    public function clearIsTest()
    {
        unset($this->IsTest);
    }

    /**
     * Generated from protobuf field <code>optional bool IsTest = 15;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsTest($var)
    {
        GPBUtil::checkBool($var);
        $this->IsTest = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsInternal = 16;</code>
     * @return bool
     */
    public function getIsInternal()
    {
        return isset($this->IsInternal) ? $this->IsInternal : false;
    }

    public function hasIsInternal()
    {
        return isset($this->IsInternal);
    }

    public function clearIsInternal()
    {
        unset($this->IsInternal);
    }

    /**
     * Generated from protobuf field <code>optional bool IsInternal = 16;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsInternal($var)
    {
        GPBUtil::checkBool($var);
        $this->IsInternal = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsProxified = 17;</code>
     * @return bool
     */
    public function getIsProxified()
    {
        return isset($this->IsProxified) ? $this->IsProxified : false;
    }

    public function hasIsProxified()
    {
        return isset($this->IsProxified);
    }

    public function clearIsProxified()
    {
        unset($this->IsProxified);
    }

    /**
     * Generated from protobuf field <code>optional bool IsProxified = 17;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsProxified($var)
    {
        GPBUtil::checkBool($var);
        $this->IsProxified = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ProxyBoxId = 18;</code>
     * @return string
     */
    public function getProxyBoxId()
    {
        return isset($this->ProxyBoxId) ? $this->ProxyBoxId : '';
    }

    public function hasProxyBoxId()
    {
        return isset($this->ProxyBoxId);
    }

    public function clearProxyBoxId()
    {
        unset($this->ProxyBoxId);
    }

    /**
     * Generated from protobuf field <code>optional string ProxyBoxId = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setProxyBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ProxyBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ProxyTitle = 19;</code>
     * @return string
     */
    public function getProxyTitle()
    {
        return isset($this->ProxyTitle) ? $this->ProxyTitle : '';
    }

    public function hasProxyTitle()
    {
        return isset($this->ProxyTitle);
    }

    public function clearProxyTitle()
    {
        unset($this->ProxyTitle);
    }

    /**
     * Generated from protobuf field <code>optional string ProxyTitle = 19;</code>
     * @param string $var
     * @return $this
     */
    public function setProxyTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->ProxyTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool PacketIsLocked = 20;</code>
     * @return bool
     */
    public function getPacketIsLocked()
    {
        return isset($this->PacketIsLocked) ? $this->PacketIsLocked : false;
    }

    public function hasPacketIsLocked()
    {
        return isset($this->PacketIsLocked);
    }

    public function clearPacketIsLocked()
    {
        unset($this->PacketIsLocked);
    }

    /**
     * Generated from protobuf field <code>optional bool PacketIsLocked = 20;</code>
     * @param bool $var
     * @return $this
     */
    public function setPacketIsLocked($var)
    {
        GPBUtil::checkBool($var);
        $this->PacketIsLocked = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.LockMode LockMode = 21;</code>
     * @return int
     */
    public function getLockMode()
    {
        return $this->LockMode;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.LockMode LockMode = 21;</code>
     * @param int $var
     * @return $this
     */
    public function setLockMode($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\LockMode::class);
        $this->LockMode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Documents.MessageType MessageType = 22;</code>
     * @return int
     */
    public function getMessageType()
    {
        return $this->MessageType;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Documents.MessageType MessageType = 22;</code>
     * @param int $var
     * @return $this
     */
    public function setMessageType($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Documents\MessageType::class);
        $this->MessageType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Events.TemplateToLetterTransformationInfo TemplateToLetterTransformationInfo = 23;</code>
     * @return \Diadoc\Api\Proto\Events\TemplateToLetterTransformationInfo|null
     */
    public function getTemplateToLetterTransformationInfo()
    {
        return $this->TemplateToLetterTransformationInfo;
    }

    public function hasTemplateToLetterTransformationInfo()
    {
        return isset($this->TemplateToLetterTransformationInfo);
    }

    public function clearTemplateToLetterTransformationInfo()
    {
        unset($this->TemplateToLetterTransformationInfo);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Events.TemplateToLetterTransformationInfo TemplateToLetterTransformationInfo = 23;</code>
     * @param \Diadoc\Api\Proto\Events\TemplateToLetterTransformationInfo $var
     * @return $this
     */
    public function setTemplateToLetterTransformationInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Events\TemplateToLetterTransformationInfo::class);
        $this->TemplateToLetterTransformationInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsReusable = 24;</code>
     * @return bool
     */
    public function getIsReusable()
    {
        return isset($this->IsReusable) ? $this->IsReusable : false;
    }

    public function hasIsReusable()
    {
        return isset($this->IsReusable);
    }

    public function clearIsReusable()
    {
        unset($this->IsReusable);
    }

    /**
     * Generated from protobuf field <code>optional bool IsReusable = 24;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsReusable($var)
    {
        GPBUtil::checkBool($var);
        $this->IsReusable = $var;

        return $this;
    }

}

