<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events/DiadocMessage-GetApi.proto

namespace Diadoc\Api\Proto\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Events.TemplateToLetterTransformationInfo</code>
 */
class TemplateToLetterTransformationInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string LetterFromBoxId = 1;</code>
     */
    protected $LetterFromBoxId = '';
    /**
     * Generated from protobuf field <code>string LetterToBoxId = 2;</code>
     */
    protected $LetterToBoxId = '';
    /**
     * Generated from protobuf field <code>optional string LetterFromDepartmentId = 3;</code>
     */
    protected $LetterFromDepartmentId = null;
    /**
     * Generated from protobuf field <code>optional string LetterToDepartmentId = 4;</code>
     */
    protected $LetterToDepartmentId = null;
    /**
     * Generated from protobuf field <code>optional string LetterProxyBoxId = 5;</code>
     */
    protected $LetterProxyBoxId = null;
    /**
     * Generated from protobuf field <code>optional string LetterProxyDepartmentId = 6;</code>
     */
    protected $LetterProxyDepartmentId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $LetterFromBoxId
     *     @type string $LetterToBoxId
     *     @type string $LetterFromDepartmentId
     *     @type string $LetterToDepartmentId
     *     @type string $LetterProxyBoxId
     *     @type string $LetterProxyDepartmentId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events\DiadocMessageGetApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string LetterFromBoxId = 1;</code>
     * @return string
     */
    public function getLetterFromBoxId()
    {
        return $this->LetterFromBoxId;
    }

    /**
     * Generated from protobuf field <code>string LetterFromBoxId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setLetterFromBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->LetterFromBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string LetterToBoxId = 2;</code>
     * @return string
     */
    public function getLetterToBoxId()
    {
        return $this->LetterToBoxId;
    }

    /**
     * Generated from protobuf field <code>string LetterToBoxId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLetterToBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->LetterToBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string LetterFromDepartmentId = 3;</code>
     * @return string
     */
    public function getLetterFromDepartmentId()
    {
        return isset($this->LetterFromDepartmentId) ? $this->LetterFromDepartmentId : '';
    }

    public function hasLetterFromDepartmentId()
    {
        return isset($this->LetterFromDepartmentId);
    }

    public function clearLetterFromDepartmentId()
    {
        unset($this->LetterFromDepartmentId);
    }

    /**
     * Generated from protobuf field <code>optional string LetterFromDepartmentId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setLetterFromDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->LetterFromDepartmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string LetterToDepartmentId = 4;</code>
     * @return string
     */
    public function getLetterToDepartmentId()
    {
        return isset($this->LetterToDepartmentId) ? $this->LetterToDepartmentId : '';
    }

    public function hasLetterToDepartmentId()
    {
        return isset($this->LetterToDepartmentId);
    }

    public function clearLetterToDepartmentId()
    {
        unset($this->LetterToDepartmentId);
    }

    /**
     * Generated from protobuf field <code>optional string LetterToDepartmentId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setLetterToDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->LetterToDepartmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string LetterProxyBoxId = 5;</code>
     * @return string
     */
    public function getLetterProxyBoxId()
    {
        return isset($this->LetterProxyBoxId) ? $this->LetterProxyBoxId : '';
    }

    public function hasLetterProxyBoxId()
    {
        return isset($this->LetterProxyBoxId);
    }

    public function clearLetterProxyBoxId()
    {
        unset($this->LetterProxyBoxId);
    }

    /**
     * Generated from protobuf field <code>optional string LetterProxyBoxId = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setLetterProxyBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->LetterProxyBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string LetterProxyDepartmentId = 6;</code>
     * @return string
     */
    public function getLetterProxyDepartmentId()
    {
        return isset($this->LetterProxyDepartmentId) ? $this->LetterProxyDepartmentId : '';
    }

    public function hasLetterProxyDepartmentId()
    {
        return isset($this->LetterProxyDepartmentId);
    }

    public function clearLetterProxyDepartmentId()
    {
        unset($this->LetterProxyDepartmentId);
    }

    /**
     * Generated from protobuf field <code>optional string LetterProxyDepartmentId = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setLetterProxyDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->LetterProxyDepartmentId = $var;

        return $this;
    }

}

