<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events/DiadocMessage-GetApi.proto

namespace Diadoc\Api\Proto\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Events.TemplateRefusalInfo</code>
 */
class TemplateRefusalInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Events.TemplateRefusalType Type = 1;</code>
     */
    protected $Type = 0;
    /**
     * Generated from protobuf field <code>string BoxId = 2;</code>
     */
    protected $BoxId = '';
    /**
     * Generated from protobuf field <code>optional string Author = 3;</code>
     */
    protected $Author = null;
    /**
     * Generated from protobuf field <code>optional string Comment = 4;</code>
     */
    protected $Comment = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Type
     *     @type string $BoxId
     *     @type string $Author
     *     @type string $Comment
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events\DiadocMessageGetApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Events.TemplateRefusalType Type = 1;</code>
     * @return int
     */
    public function getType()
    {
        return $this->Type;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Events.TemplateRefusalType Type = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setType($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Events\TemplateRefusalType::class);
        $this->Type = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string BoxId = 2;</code>
     * @return string
     */
    public function getBoxId()
    {
        return $this->BoxId;
    }

    /**
     * Generated from protobuf field <code>string BoxId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->BoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Author = 3;</code>
     * @return string
     */
    public function getAuthor()
    {
        return isset($this->Author) ? $this->Author : '';
    }

    public function hasAuthor()
    {
        return isset($this->Author);
    }

    public function clearAuthor()
    {
        unset($this->Author);
    }

    /**
     * Generated from protobuf field <code>optional string Author = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthor($var)
    {
        GPBUtil::checkString($var, True);
        $this->Author = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Comment = 4;</code>
     * @return string
     */
    public function getComment()
    {
        return isset($this->Comment) ? $this->Comment : '';
    }

    public function hasComment()
    {
        return isset($this->Comment);
    }

    public function clearComment()
    {
        unset($this->Comment);
    }

    /**
     * Generated from protobuf field <code>optional string Comment = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setComment($var)
    {
        GPBUtil::checkString($var, True);
        $this->Comment = $var;

        return $this;
    }

}

