<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Events/DiadocMessage-PostApi.proto

namespace Diadoc\Api\Proto\Events;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Events.TemplateToPost</code>
 */
class TemplateToPost extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string FromBoxId = 1;</code>
     */
    protected $FromBoxId = '';
    /**
     * Generated from protobuf field <code>string ToBoxId = 2;</code>
     */
    protected $ToBoxId = '';
    /**
     * Generated from protobuf field <code>string MessageFromBoxId = 3;</code>
     */
    protected $MessageFromBoxId = '';
    /**
     * Generated from protobuf field <code>string MessageToBoxId = 4;</code>
     */
    protected $MessageToBoxId = '';
    /**
     * Generated from protobuf field <code>optional string MessageToDepartmentId = 5;</code>
     */
    protected $MessageToDepartmentId = null;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Events.TemplateDocumentAttachment DocumentAttachments = 6;</code>
     */
    private $DocumentAttachments;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.LockMode LockMode = 7;</code>
     */
    protected $LockMode = null;
    /**
     * Generated from protobuf field <code>optional string FromDepartmentId = 8;</code>
     */
    protected $FromDepartmentId = null;
    /**
     * Generated from protobuf field <code>optional string ToDepartmentId = 9;</code>
     */
    protected $ToDepartmentId = null;
    /**
     * Generated from protobuf field <code>optional string MessageProxyBoxId = 10;</code>
     */
    protected $MessageProxyBoxId = null;
    /**
     * Generated from protobuf field <code>optional string MessageProxyDepartmentId = 11;</code>
     */
    protected $MessageProxyDepartmentId = null;
    /**
     * Generated from protobuf field <code>optional bool IsReusable = 12;</code>
     */
    protected $IsReusable = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $FromBoxId
     *     @type string $ToBoxId
     *     @type string $MessageFromBoxId
     *     @type string $MessageToBoxId
     *     @type string $MessageToDepartmentId
     *     @type array<\Diadoc\Api\Proto\Events\TemplateDocumentAttachment>|\Google\Protobuf\Internal\RepeatedField $DocumentAttachments
     *     @type int $LockMode
     *     @type string $FromDepartmentId
     *     @type string $ToDepartmentId
     *     @type string $MessageProxyBoxId
     *     @type string $MessageProxyDepartmentId
     *     @type bool $IsReusable
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Events\DiadocMessagePostApi::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string FromBoxId = 1;</code>
     * @return string
     */
    public function getFromBoxId()
    {
        return $this->FromBoxId;
    }

    /**
     * Generated from protobuf field <code>string FromBoxId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setFromBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FromBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string ToBoxId = 2;</code>
     * @return string
     */
    public function getToBoxId()
    {
        return $this->ToBoxId;
    }

    /**
     * Generated from protobuf field <code>string ToBoxId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setToBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string MessageFromBoxId = 3;</code>
     * @return string
     */
    public function getMessageFromBoxId()
    {
        return $this->MessageFromBoxId;
    }

    /**
     * Generated from protobuf field <code>string MessageFromBoxId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageFromBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageFromBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string MessageToBoxId = 4;</code>
     * @return string
     */
    public function getMessageToBoxId()
    {
        return $this->MessageToBoxId;
    }

    /**
     * Generated from protobuf field <code>string MessageToBoxId = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageToBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageToBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string MessageToDepartmentId = 5;</code>
     * @return string
     */
    public function getMessageToDepartmentId()
    {
        return isset($this->MessageToDepartmentId) ? $this->MessageToDepartmentId : '';
    }

    public function hasMessageToDepartmentId()
    {
        return isset($this->MessageToDepartmentId);
    }

    public function clearMessageToDepartmentId()
    {
        unset($this->MessageToDepartmentId);
    }

    /**
     * Generated from protobuf field <code>optional string MessageToDepartmentId = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageToDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageToDepartmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Events.TemplateDocumentAttachment DocumentAttachments = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getDocumentAttachments()
    {
        return $this->DocumentAttachments;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Events.TemplateDocumentAttachment DocumentAttachments = 6;</code>
     * @param array<\Diadoc\Api\Proto\Events\TemplateDocumentAttachment>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setDocumentAttachments($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Events\TemplateDocumentAttachment::class);
        $this->DocumentAttachments = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.LockMode LockMode = 7;</code>
     * @return int
     */
    public function getLockMode()
    {
        return isset($this->LockMode) ? $this->LockMode : 0;
    }

    public function hasLockMode()
    {
        return isset($this->LockMode);
    }

    public function clearLockMode()
    {
        unset($this->LockMode);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.LockMode LockMode = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setLockMode($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\LockMode::class);
        $this->LockMode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string FromDepartmentId = 8;</code>
     * @return string
     */
    public function getFromDepartmentId()
    {
        return isset($this->FromDepartmentId) ? $this->FromDepartmentId : '';
    }

    public function hasFromDepartmentId()
    {
        return isset($this->FromDepartmentId);
    }

    public function clearFromDepartmentId()
    {
        unset($this->FromDepartmentId);
    }

    /**
     * Generated from protobuf field <code>optional string FromDepartmentId = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setFromDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->FromDepartmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ToDepartmentId = 9;</code>
     * @return string
     */
    public function getToDepartmentId()
    {
        return isset($this->ToDepartmentId) ? $this->ToDepartmentId : '';
    }

    public function hasToDepartmentId()
    {
        return isset($this->ToDepartmentId);
    }

    public function clearToDepartmentId()
    {
        unset($this->ToDepartmentId);
    }

    /**
     * Generated from protobuf field <code>optional string ToDepartmentId = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setToDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ToDepartmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string MessageProxyBoxId = 10;</code>
     * @return string
     */
    public function getMessageProxyBoxId()
    {
        return isset($this->MessageProxyBoxId) ? $this->MessageProxyBoxId : '';
    }

    public function hasMessageProxyBoxId()
    {
        return isset($this->MessageProxyBoxId);
    }

    public function clearMessageProxyBoxId()
    {
        unset($this->MessageProxyBoxId);
    }

    /**
     * Generated from protobuf field <code>optional string MessageProxyBoxId = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageProxyBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageProxyBoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string MessageProxyDepartmentId = 11;</code>
     * @return string
     */
    public function getMessageProxyDepartmentId()
    {
        return isset($this->MessageProxyDepartmentId) ? $this->MessageProxyDepartmentId : '';
    }

    public function hasMessageProxyDepartmentId()
    {
        return isset($this->MessageProxyDepartmentId);
    }

    public function clearMessageProxyDepartmentId()
    {
        unset($this->MessageProxyDepartmentId);
    }

    /**
     * Generated from protobuf field <code>optional string MessageProxyDepartmentId = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setMessageProxyDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->MessageProxyDepartmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool IsReusable = 12;</code>
     * @return bool
     */
    public function getIsReusable()
    {
        return isset($this->IsReusable) ? $this->IsReusable : false;
    }

    public function hasIsReusable()
    {
        return isset($this->IsReusable);
    }

    public function clearIsReusable()
    {
        unset($this->IsReusable);
    }

    /**
     * Generated from protobuf field <code>optional bool IsReusable = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsReusable($var)
    {
        GPBUtil::checkBool($var);
        $this->IsReusable = $var;

        return $this;
    }

}

