<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Organizations/BlockStatus.proto

namespace GPBMetadata\Organizations;

class BlockStatus
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Organizations\ManualBlockStatus::initOnce();
        \GPBMetadata\Organizations\AutoBlockStatus::initOnce();
        $pool->internalAddGeneratedFile(
            '
–
Organizations/BlockStatus.protoDiadoc.Api.Proto.Organizations#Organizations/AutoBlockStatus.proto"¥
BlockStatusL
ManualBlockStatus (21.Diadoc.Api.Proto.Organizations.ManualBlockStatusH
AutoBlockStatus (2/.Diadoc.Api.Proto.Organizations.AutoBlockStatusbproto3'
        , true);

        static::$is_initialized = true;
    }
}

