<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Departments/DepartmentToUpdate.proto

namespace Diadoc\Api\Proto\Departments;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Departments.ParentDepartmentPatch</code>
 */
class ParentDepartmentPatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string ParentDepartmentId = 1;</code>
     */
    protected $ParentDepartmentId = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ParentDepartmentId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Departments\DepartmentToUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string ParentDepartmentId = 1;</code>
     * @return string
     */
    public function getParentDepartmentId()
    {
        return $this->ParentDepartmentId;
    }

    /**
     * Generated from protobuf field <code>string ParentDepartmentId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setParentDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParentDepartmentId = $var;

        return $this;
    }

}

