<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/ReceiptGenerationRequest.proto

namespace GPBMetadata\Invoicing;

class ReceiptGenerationRequest
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
¬
(Invoicing/ReceiptGenerationRequest.protoDiadoc.Api.Proto.Invoicing"\\
ReceiptGenerationRequestV2
	MessageId (	
AttachmentId (	
SignerContent (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

