<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Certificates/CertificateList.proto

namespace GPBMetadata\Certificates;

class CertificateList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Certificates\CertificateInfoV2::initOnce();
        $pool->internalAddGeneratedFile(
            '
¦
"Certificates/CertificateList.protoDiadoc.Api.Proto.Certificates"Y
CertificateListF
Certificates (20.Diadoc.Api.Proto.Certificates.CertificateInfoV2bproto3'
        , true);

        static::$is_initialized = true;
    }
}

