<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Documents/Types/DocumentTypeDescription.proto

namespace GPBMetadata\Documents\Types;

class DocumentTypeDescription
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
—
-Documents/Types/DocumentTypeDescription.proto Diadoc.Api.Proto.Documents.Types"N
DetectedDocumentType
TypeNamedId (	
Function (	
Version (	"l
DetectDocumentTypesResponseM
DocumentTypes (26.Diadoc.Api.Proto.Documents.Types.DetectedDocumentTypebproto3'
        , true);

        static::$is_initialized = true;
    }
}

