<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/RoamingNotification.proto

namespace GPBMetadata\Docflow;

class RoamingNotification
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Docflow\Attachment::initOnce();
        $pool->internalAddGeneratedFile(
            '
§
!Docflow/RoamingNotification.protoDiadoc.Api.Proto.Docflow"`
RoamingNotification6
Notification (2 .Diadoc.Api.Proto.Docflow.Entity
	IsSuccess (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

