<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CounteragentGroups/CounteragentGroup.proto

namespace Diadoc\Api\Proto\CounteragentGroups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.CounteragentGroups.CounteragentGroup</code>
 */
class CounteragentGroup extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string CounteragentGroupId = 1;</code>
     */
    protected $CounteragentGroupId = '';
    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     */
    protected $Name = '';
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 3;</code>
     */
    protected $Departments = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $CounteragentGroupId
     *     @type string $Name
     *     @type \Diadoc\Api\Proto\CounteragentGroups\DepartmentsInGroup $Departments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CounteragentGroups\CounteragentGroup::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string CounteragentGroupId = 1;</code>
     * @return string
     */
    public function getCounteragentGroupId()
    {
        return $this->CounteragentGroupId;
    }

    /**
     * Generated from protobuf field <code>string CounteragentGroupId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setCounteragentGroupId($var)
    {
        GPBUtil::checkString($var, True);
        $this->CounteragentGroupId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @return string
     */
    public function getName()
    {
        return $this->Name;
    }

    /**
     * Generated from protobuf field <code>string Name = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setName($var)
    {
        GPBUtil::checkString($var, True);
        $this->Name = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 3;</code>
     * @return \Diadoc\Api\Proto\CounteragentGroups\DepartmentsInGroup|null
     */
    public function getDepartments()
    {
        return $this->Departments;
    }

    public function hasDepartments()
    {
        return isset($this->Departments);
    }

    public function clearDepartments()
    {
        unset($this->Departments);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.CounteragentGroups.DepartmentsInGroup Departments = 3;</code>
     * @param \Diadoc\Api\Proto\CounteragentGroups\DepartmentsInGroup $var
     * @return $this
     */
    public function setDepartments($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\CounteragentGroups\DepartmentsInGroup::class);
        $this->Departments = $var;

        return $this;
    }

}

