<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CounteragentGroups/CounteragentGroup.proto

namespace Diadoc\Api\Proto\CounteragentGroups;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.CounteragentGroups.CounteragentGroupsList</code>
 */
class CounteragentGroupsList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroup Groups = 1;</code>
     */
    private $Groups;
    /**
     * Generated from protobuf field <code>int32 TotalCount = 2;</code>
     */
    protected $TotalCount = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Diadoc\Api\Proto\CounteragentGroups\CounteragentGroup>|\Google\Protobuf\Internal\RepeatedField $Groups
     *     @type int $TotalCount
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CounteragentGroups\CounteragentGroup::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroup Groups = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGroups()
    {
        return $this->Groups;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.CounteragentGroups.CounteragentGroup Groups = 1;</code>
     * @param array<\Diadoc\Api\Proto\CounteragentGroups\CounteragentGroup>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGroups($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\CounteragentGroups\CounteragentGroup::class);
        $this->Groups = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 TotalCount = 2;</code>
     * @return int
     */
    public function getTotalCount()
    {
        return $this->TotalCount;
    }

    /**
     * Generated from protobuf field <code>int32 TotalCount = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setTotalCount($var)
    {
        GPBUtil::checkInt32($var);
        $this->TotalCount = $var;

        return $this;
    }

}

