<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Employees/EmployeeToUpdate.proto

namespace Diadoc\Api\Proto\Employees;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Employees.EmployeePositionPatch</code>
 */
class EmployeePositionPatch extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Position = 1;</code>
     */
    protected $Position = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Position
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Employees\EmployeeToUpdate::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Position = 1;</code>
     * @return string
     */
    public function getPosition()
    {
        return isset($this->Position) ? $this->Position : '';
    }

    public function hasPosition()
    {
        return isset($this->Position);
    }

    public function clearPosition()
    {
        unset($this->Position);
    }

    /**
     * Generated from protobuf field <code>optional string Position = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setPosition($var)
    {
        GPBUtil::checkString($var, True);
        $this->Position = $var;

        return $this;
    }

}

