<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AcquireCounteragent.proto

namespace Diadoc\Api\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.AcquireCounteragentResult</code>
 */
class AcquireCounteragentResult extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string OrgId = 1;</code>
     */
    protected $OrgId = '';
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId InvitationDocumentId = 2;</code>
     */
    protected $InvitationDocumentId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $OrgId
     *     @type \Diadoc\Api\Proto\DocumentId $InvitationDocumentId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\AcquireCounteragent::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string OrgId = 1;</code>
     * @return string
     */
    public function getOrgId()
    {
        return $this->OrgId;
    }

    /**
     * Generated from protobuf field <code>string OrgId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOrgId($var)
    {
        GPBUtil::checkString($var, True);
        $this->OrgId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId InvitationDocumentId = 2;</code>
     * @return \Diadoc\Api\Proto\DocumentId|null
     */
    public function getInvitationDocumentId()
    {
        return $this->InvitationDocumentId;
    }

    public function hasInvitationDocumentId()
    {
        return isset($this->InvitationDocumentId);
    }

    public function clearInvitationDocumentId()
    {
        unset($this->InvitationDocumentId);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId InvitationDocumentId = 2;</code>
     * @param \Diadoc\Api\Proto\DocumentId $var
     * @return $this
     */
    public function setInvitationDocumentId($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\DocumentId::class);
        $this->InvitationDocumentId = $var;

        return $this;
    }

}

