<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Organization.proto

namespace Diadoc\Api\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Box</code>
 */
class Box extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string BoxId = 1;</code>
     */
    protected $BoxId = '';
    /**
     * Generated from protobuf field <code>string BoxIdGuid = 6;</code>
     */
    protected $BoxIdGuid = '';
    /**
     * Generated from protobuf field <code>string Title = 2;</code>
     */
    protected $Title = '';
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Organization Organization = 3;</code>
     */
    protected $Organization = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.OrganizationInvoiceFormatVersion InvoiceFormatVersion = 4;</code>
     */
    protected $InvoiceFormatVersion = null;
    /**
     * Generated from protobuf field <code>optional bool EncryptedDocumentsAllowed = 5;</code>
     */
    protected $EncryptedDocumentsAllowed = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $BoxId
     *     @type string $BoxIdGuid
     *     @type string $Title
     *     @type \Diadoc\Api\Proto\Organization $Organization
     *     @type int $InvoiceFormatVersion
     *     @type bool $EncryptedDocumentsAllowed
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Organization::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string BoxId = 1;</code>
     * @return string
     */
    public function getBoxId()
    {
        return $this->BoxId;
    }

    /**
     * Generated from protobuf field <code>string BoxId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setBoxId($var)
    {
        GPBUtil::checkString($var, True);
        $this->BoxId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string BoxIdGuid = 6;</code>
     * @return string
     */
    public function getBoxIdGuid()
    {
        return $this->BoxIdGuid;
    }

    /**
     * Generated from protobuf field <code>string BoxIdGuid = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setBoxIdGuid($var)
    {
        GPBUtil::checkString($var, True);
        $this->BoxIdGuid = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>string Title = 2;</code>
     * @return string
     */
    public function getTitle()
    {
        return $this->Title;
    }

    /**
     * Generated from protobuf field <code>string Title = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->Title = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Organization Organization = 3;</code>
     * @return \Diadoc\Api\Proto\Organization|null
     */
    public function getOrganization()
    {
        return $this->Organization;
    }

    public function hasOrganization()
    {
        return isset($this->Organization);
    }

    public function clearOrganization()
    {
        unset($this->Organization);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Organization Organization = 3;</code>
     * @param \Diadoc\Api\Proto\Organization $var
     * @return $this
     */
    public function setOrganization($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Organization::class);
        $this->Organization = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.OrganizationInvoiceFormatVersion InvoiceFormatVersion = 4;</code>
     * @return int
     */
    public function getInvoiceFormatVersion()
    {
        return isset($this->InvoiceFormatVersion) ? $this->InvoiceFormatVersion : 0;
    }

    public function hasInvoiceFormatVersion()
    {
        return isset($this->InvoiceFormatVersion);
    }

    public function clearInvoiceFormatVersion()
    {
        unset($this->InvoiceFormatVersion);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.OrganizationInvoiceFormatVersion InvoiceFormatVersion = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setInvoiceFormatVersion($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\OrganizationInvoiceFormatVersion::class);
        $this->InvoiceFormatVersion = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool EncryptedDocumentsAllowed = 5;</code>
     * @return bool
     */
    public function getEncryptedDocumentsAllowed()
    {
        return isset($this->EncryptedDocumentsAllowed) ? $this->EncryptedDocumentsAllowed : false;
    }

    public function hasEncryptedDocumentsAllowed()
    {
        return isset($this->EncryptedDocumentsAllowed);
    }

    public function clearEncryptedDocumentsAllowed()
    {
        unset($this->EncryptedDocumentsAllowed);
    }

    /**
     * Generated from protobuf field <code>optional bool EncryptedDocumentsAllowed = 5;</code>
     * @param bool $var
     * @return $this
     */
    public function setEncryptedDocumentsAllowed($var)
    {
        GPBUtil::checkBool($var);
        $this->EncryptedDocumentsAllowed = $var;

        return $this;
    }

}

