<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CloudSign.proto

namespace Diadoc\Api\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.CloudSignFile</code>
 */
class CloudSignFile extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Content_v2 Content = 1;</code>
     */
    protected $Content = null;
    /**
     * Generated from protobuf field <code>optional string FileName = 2;</code>
     */
    protected $FileName = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Api\Proto\Content_v2 $Content
     *     @type string $FileName
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\CloudSign::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Content_v2 Content = 1;</code>
     * @return \Diadoc\Api\Proto\Content_v2|null
     */
    public function getContent()
    {
        return $this->Content;
    }

    public function hasContent()
    {
        return isset($this->Content);
    }

    public function clearContent()
    {
        unset($this->Content);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Content_v2 Content = 1;</code>
     * @param \Diadoc\Api\Proto\Content_v2 $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Content_v2::class);
        $this->Content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string FileName = 2;</code>
     * @return string
     */
    public function getFileName()
    {
        return isset($this->FileName) ? $this->FileName : '';
    }

    public function hasFileName()
    {
        return isset($this->FileName);
    }

    public function clearFileName()
    {
        unset($this->FileName);
    }

    /**
     * Generated from protobuf field <code>optional string FileName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setFileName($var)
    {
        GPBUtil::checkString($var, True);
        $this->FileName = $var;

        return $this;
    }

}

