<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Content_v2.proto

namespace Diadoc\Api\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Content_v2</code>
 */
class Content_v2 extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bytes Content = 1;</code>
     */
    protected $Content = null;
    /**
     * Generated from protobuf field <code>optional string NameOnShelf = 2;</code>
     */
    protected $NameOnShelf = null;
    /**
     * Generated from protobuf field <code>optional string PatchedContentId = 3;</code>
     */
    protected $PatchedContentId = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentIdEx DocumentId = 4;</code>
     */
    protected $DocumentId = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Content
     *     @type string $NameOnShelf
     *     @type string $PatchedContentId
     *     @type \Diadoc\Api\Proto\DocumentIdEx $DocumentId
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\ContentV2::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bytes Content = 1;</code>
     * @return string
     */
    public function getContent()
    {
        return isset($this->Content) ? $this->Content : '';
    }

    public function hasContent()
    {
        return isset($this->Content);
    }

    public function clearContent()
    {
        unset($this->Content);
    }

    /**
     * Generated from protobuf field <code>optional bytes Content = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkString($var, False);
        $this->Content = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string NameOnShelf = 2;</code>
     * @return string
     */
    public function getNameOnShelf()
    {
        return isset($this->NameOnShelf) ? $this->NameOnShelf : '';
    }

    public function hasNameOnShelf()
    {
        return isset($this->NameOnShelf);
    }

    public function clearNameOnShelf()
    {
        unset($this->NameOnShelf);
    }

    /**
     * Generated from protobuf field <code>optional string NameOnShelf = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setNameOnShelf($var)
    {
        GPBUtil::checkString($var, True);
        $this->NameOnShelf = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string PatchedContentId = 3;</code>
     * @return string
     */
    public function getPatchedContentId()
    {
        return isset($this->PatchedContentId) ? $this->PatchedContentId : '';
    }

    public function hasPatchedContentId()
    {
        return isset($this->PatchedContentId);
    }

    public function clearPatchedContentId()
    {
        unset($this->PatchedContentId);
    }

    /**
     * Generated from protobuf field <code>optional string PatchedContentId = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPatchedContentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->PatchedContentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentIdEx DocumentId = 4;</code>
     * @return \Diadoc\Api\Proto\DocumentIdEx|null
     */
    public function getDocumentId()
    {
        return $this->DocumentId;
    }

    public function hasDocumentId()
    {
        return isset($this->DocumentId);
    }

    public function clearDocumentId()
    {
        unset($this->DocumentId);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentIdEx DocumentId = 4;</code>
     * @param \Diadoc\Api\Proto\DocumentIdEx $var
     * @return $this
     */
    public function setDocumentId($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\DocumentIdEx::class);
        $this->DocumentId = $var;

        return $this;
    }

}

