<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OrganizationUserPermissions.proto

namespace Diadoc\Api\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.OrganizationUserPermissions</code>
 */
class OrganizationUserPermissions extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string UserDepartmentId = 1;</code>
     */
    protected $UserDepartmentId = '';
    /**
     * Generated from protobuf field <code>bool IsAdministrator = 2;</code>
     */
    protected $IsAdministrator = false;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentAccessLevel DocumentAccessLevel = 3;</code>
     */
    protected $DocumentAccessLevel = null;
    /**
     * Generated from protobuf field <code>bool CanSignDocuments = 4;</code>
     */
    protected $CanSignDocuments = false;
    /**
     * Generated from protobuf field <code>bool CanManageCounteragents = 6;</code>
     */
    protected $CanManageCounteragents = false;
    /**
     * Generated from protobuf field <code>bool CanAddResolutions = 7;</code>
     */
    protected $CanAddResolutions = false;
    /**
     * Generated from protobuf field <code>bool CanRequestResolutions = 8;</code>
     */
    protected $CanRequestResolutions = false;
    /**
     * Generated from protobuf field <code>repeated string SelectedDepartmentIds = 9;</code>
     */
    private $SelectedDepartmentIds;
    /**
     * Generated from protobuf field <code>optional string JobTitle = 10;</code>
     */
    protected $JobTitle = null;
    /**
     * Generated from protobuf field <code>bool CanCreateDocuments = 11;</code>
     */
    protected $CanCreateDocuments = false;
    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.AuthorizationPermission AuthorizationPermission = 12;</code>
     */
    protected $AuthorizationPermission = null;
    /**
     * Generated from protobuf field <code>bool CanDeleteRestoreDocuments = 13;</code>
     */
    protected $CanDeleteRestoreDocuments = false;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $UserDepartmentId
     *     @type bool $IsAdministrator
     *     @type int $DocumentAccessLevel
     *     @type bool $CanSignDocuments
     *     @type bool $CanManageCounteragents
     *     @type bool $CanAddResolutions
     *     @type bool $CanRequestResolutions
     *     @type array<string>|\Google\Protobuf\Internal\RepeatedField $SelectedDepartmentIds
     *     @type string $JobTitle
     *     @type bool $CanCreateDocuments
     *     @type \Diadoc\Api\Proto\AuthorizationPermission $AuthorizationPermission
     *     @type bool $CanDeleteRestoreDocuments
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\OrganizationUserPermissions::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string UserDepartmentId = 1;</code>
     * @return string
     */
    public function getUserDepartmentId()
    {
        return $this->UserDepartmentId;
    }

    /**
     * Generated from protobuf field <code>string UserDepartmentId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUserDepartmentId($var)
    {
        GPBUtil::checkString($var, True);
        $this->UserDepartmentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool IsAdministrator = 2;</code>
     * @return bool
     */
    public function getIsAdministrator()
    {
        return $this->IsAdministrator;
    }

    /**
     * Generated from protobuf field <code>bool IsAdministrator = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsAdministrator($var)
    {
        GPBUtil::checkBool($var);
        $this->IsAdministrator = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentAccessLevel DocumentAccessLevel = 3;</code>
     * @return int
     */
    public function getDocumentAccessLevel()
    {
        return isset($this->DocumentAccessLevel) ? $this->DocumentAccessLevel : 0;
    }

    public function hasDocumentAccessLevel()
    {
        return isset($this->DocumentAccessLevel);
    }

    public function clearDocumentAccessLevel()
    {
        unset($this->DocumentAccessLevel);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentAccessLevel DocumentAccessLevel = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setDocumentAccessLevel($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\DocumentAccessLevel::class);
        $this->DocumentAccessLevel = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool CanSignDocuments = 4;</code>
     * @return bool
     */
    public function getCanSignDocuments()
    {
        return $this->CanSignDocuments;
    }

    /**
     * Generated from protobuf field <code>bool CanSignDocuments = 4;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanSignDocuments($var)
    {
        GPBUtil::checkBool($var);
        $this->CanSignDocuments = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool CanManageCounteragents = 6;</code>
     * @return bool
     */
    public function getCanManageCounteragents()
    {
        return $this->CanManageCounteragents;
    }

    /**
     * Generated from protobuf field <code>bool CanManageCounteragents = 6;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanManageCounteragents($var)
    {
        GPBUtil::checkBool($var);
        $this->CanManageCounteragents = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool CanAddResolutions = 7;</code>
     * @return bool
     */
    public function getCanAddResolutions()
    {
        return $this->CanAddResolutions;
    }

    /**
     * Generated from protobuf field <code>bool CanAddResolutions = 7;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanAddResolutions($var)
    {
        GPBUtil::checkBool($var);
        $this->CanAddResolutions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool CanRequestResolutions = 8;</code>
     * @return bool
     */
    public function getCanRequestResolutions()
    {
        return $this->CanRequestResolutions;
    }

    /**
     * Generated from protobuf field <code>bool CanRequestResolutions = 8;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanRequestResolutions($var)
    {
        GPBUtil::checkBool($var);
        $this->CanRequestResolutions = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated string SelectedDepartmentIds = 9;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSelectedDepartmentIds()
    {
        return $this->SelectedDepartmentIds;
    }

    /**
     * Generated from protobuf field <code>repeated string SelectedDepartmentIds = 9;</code>
     * @param array<string>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSelectedDepartmentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::STRING);
        $this->SelectedDepartmentIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string JobTitle = 10;</code>
     * @return string
     */
    public function getJobTitle()
    {
        return isset($this->JobTitle) ? $this->JobTitle : '';
    }

    public function hasJobTitle()
    {
        return isset($this->JobTitle);
    }

    public function clearJobTitle()
    {
        unset($this->JobTitle);
    }

    /**
     * Generated from protobuf field <code>optional string JobTitle = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setJobTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->JobTitle = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool CanCreateDocuments = 11;</code>
     * @return bool
     */
    public function getCanCreateDocuments()
    {
        return $this->CanCreateDocuments;
    }

    /**
     * Generated from protobuf field <code>bool CanCreateDocuments = 11;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanCreateDocuments($var)
    {
        GPBUtil::checkBool($var);
        $this->CanCreateDocuments = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.AuthorizationPermission AuthorizationPermission = 12;</code>
     * @return \Diadoc\Api\Proto\AuthorizationPermission|null
     */
    public function getAuthorizationPermission()
    {
        return $this->AuthorizationPermission;
    }

    public function hasAuthorizationPermission()
    {
        return isset($this->AuthorizationPermission);
    }

    public function clearAuthorizationPermission()
    {
        unset($this->AuthorizationPermission);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.AuthorizationPermission AuthorizationPermission = 12;</code>
     * @param \Diadoc\Api\Proto\AuthorizationPermission $var
     * @return $this
     */
    public function setAuthorizationPermission($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\AuthorizationPermission::class);
        $this->AuthorizationPermission = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>bool CanDeleteRestoreDocuments = 13;</code>
     * @return bool
     */
    public function getCanDeleteRestoreDocuments()
    {
        return $this->CanDeleteRestoreDocuments;
    }

    /**
     * Generated from protobuf field <code>bool CanDeleteRestoreDocuments = 13;</code>
     * @param bool $var
     * @return $this
     */
    public function setCanDeleteRestoreDocuments($var)
    {
        GPBUtil::checkBool($var);
        $this->CanDeleteRestoreDocuments = $var;

        return $this;
    }

}

