<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RoamingSendingStatus.proto

namespace Diadoc\Api\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.RoamingSendingStatus</code>
 */
class RoamingSendingStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Severity Severity = 1;</code>
     */
    protected $Severity = 0;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.RoamingSendingStatusNamedId StatusNamedId = 2;</code>
     */
    protected $StatusNamedId = null;
    /**
     * Generated from protobuf field <code>optional string StatusText = 3;</code>
     */
    protected $StatusText = null;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.RoamingSendingError Errors = 4;</code>
     */
    private $Errors;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Severity
     *     @type int $StatusNamedId
     *     @type string $StatusText
     *     @type array<\Diadoc\Api\Proto\RoamingSendingError>|\Google\Protobuf\Internal\RepeatedField $Errors
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\RoamingSendingStatus::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Severity Severity = 1;</code>
     * @return int
     */
    public function getSeverity()
    {
        return $this->Severity;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Severity Severity = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setSeverity($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Severity::class);
        $this->Severity = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.RoamingSendingStatusNamedId StatusNamedId = 2;</code>
     * @return int
     */
    public function getStatusNamedId()
    {
        return isset($this->StatusNamedId) ? $this->StatusNamedId : 0;
    }

    public function hasStatusNamedId()
    {
        return isset($this->StatusNamedId);
    }

    public function clearStatusNamedId()
    {
        unset($this->StatusNamedId);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.RoamingSendingStatusNamedId StatusNamedId = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatusNamedId($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\RoamingSendingStatusNamedId::class);
        $this->StatusNamedId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string StatusText = 3;</code>
     * @return string
     */
    public function getStatusText()
    {
        return isset($this->StatusText) ? $this->StatusText : '';
    }

    public function hasStatusText()
    {
        return isset($this->StatusText);
    }

    public function clearStatusText()
    {
        unset($this->StatusText);
    }

    /**
     * Generated from protobuf field <code>optional string StatusText = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setStatusText($var)
    {
        GPBUtil::checkString($var, True);
        $this->StatusText = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.RoamingSendingError Errors = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getErrors()
    {
        return $this->Errors;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.RoamingSendingError Errors = 4;</code>
     * @param array<\Diadoc\Api\Proto\RoamingSendingError>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setErrors($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\RoamingSendingError::class);
        $this->Errors = $arr;

        return $this;
    }

}

