<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Workflows/DocumentWorkflowSettings.proto

namespace Diadoc\Api\Proto\Workflows;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Workflows.DocumentWorkflowSettings</code>
 */
class DocumentWorkflowSettings extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     */
    protected $Id = 0;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Workflows.ParticipantSetting Participants = 2;</code>
     */
    private $Participants;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.OperatorConfirmationReceiptBehavior.OperatorConfirmationReceiptBehavior OperatorConfirmationReceiptBehavior = 3;</code>
     */
    protected $OperatorConfirmationReceiptBehavior = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.ReceiptOperatorConfirmationReceiptBehavior.ReceiptOperatorConfirmationReceiptBehavior ReceiptOperatorConfirmationReceiptBehavior = 4;</code>
     */
    protected $ReceiptOperatorConfirmationReceiptBehavior = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.OperatorConfirmationBehavior.OperatorConfirmationBehavior ReceiptOperatorConfirmationBehavior = 5;</code>
     */
    protected $ReceiptOperatorConfirmationBehavior = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.AmendmentRequestResponseBehavior.AmendmentRequestResponseBehavior AmendmentRequestResponseBehavior = 6;</code>
     */
    protected $AmendmentRequestResponseBehavior = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.OperatorConfirmationBehavior.OperatorConfirmationBehavior AmendmentRequestOperatorConfirmationBehavior = 7;</code>
     */
    protected $AmendmentRequestOperatorConfirmationBehavior = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.RoamingConfirmationBehavior.RoamingConfirmationBehavior ReceiptRoamingConfirmationBehavior = 8;</code>
     */
    protected $ReceiptRoamingConfirmationBehavior = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.RoamingConfirmationBehavior.RoamingConfirmationBehavior AmendmentRequestRoamingConfirmationBehavior = 9;</code>
     */
    protected $AmendmentRequestRoamingConfirmationBehavior = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.InvitationBehavior.InvitationBehavior InvitationBehavior = 10;</code>
     */
    protected $InvitationBehavior = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $Id
     *     @type array<\Diadoc\Api\Proto\Workflows\ParticipantSetting>|\Google\Protobuf\Internal\RepeatedField $Participants
     *     @type int $OperatorConfirmationReceiptBehavior
     *     @type int $ReceiptOperatorConfirmationReceiptBehavior
     *     @type int $ReceiptOperatorConfirmationBehavior
     *     @type int $AmendmentRequestResponseBehavior
     *     @type int $AmendmentRequestOperatorConfirmationBehavior
     *     @type int $ReceiptRoamingConfirmationBehavior
     *     @type int $AmendmentRequestRoamingConfirmationBehavior
     *     @type int $InvitationBehavior
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Workflows\DocumentWorkflowSettings::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     * @return int
     */
    public function getId()
    {
        return $this->Id;
    }

    /**
     * Generated from protobuf field <code>int32 Id = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setId($var)
    {
        GPBUtil::checkInt32($var);
        $this->Id = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Workflows.ParticipantSetting Participants = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getParticipants()
    {
        return $this->Participants;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Workflows.ParticipantSetting Participants = 2;</code>
     * @param array<\Diadoc\Api\Proto\Workflows\ParticipantSetting>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setParticipants($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Workflows\ParticipantSetting::class);
        $this->Participants = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.OperatorConfirmationReceiptBehavior.OperatorConfirmationReceiptBehavior OperatorConfirmationReceiptBehavior = 3;</code>
     * @return int
     */
    public function getOperatorConfirmationReceiptBehavior()
    {
        return isset($this->OperatorConfirmationReceiptBehavior) ? $this->OperatorConfirmationReceiptBehavior : 0;
    }

    public function hasOperatorConfirmationReceiptBehavior()
    {
        return isset($this->OperatorConfirmationReceiptBehavior);
    }

    public function clearOperatorConfirmationReceiptBehavior()
    {
        unset($this->OperatorConfirmationReceiptBehavior);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.OperatorConfirmationReceiptBehavior.OperatorConfirmationReceiptBehavior OperatorConfirmationReceiptBehavior = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setOperatorConfirmationReceiptBehavior($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Workflows\OperatorConfirmationReceiptBehavior\OperatorConfirmationReceiptBehavior::class);
        $this->OperatorConfirmationReceiptBehavior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.ReceiptOperatorConfirmationReceiptBehavior.ReceiptOperatorConfirmationReceiptBehavior ReceiptOperatorConfirmationReceiptBehavior = 4;</code>
     * @return int
     */
    public function getReceiptOperatorConfirmationReceiptBehavior()
    {
        return isset($this->ReceiptOperatorConfirmationReceiptBehavior) ? $this->ReceiptOperatorConfirmationReceiptBehavior : 0;
    }

    public function hasReceiptOperatorConfirmationReceiptBehavior()
    {
        return isset($this->ReceiptOperatorConfirmationReceiptBehavior);
    }

    public function clearReceiptOperatorConfirmationReceiptBehavior()
    {
        unset($this->ReceiptOperatorConfirmationReceiptBehavior);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.ReceiptOperatorConfirmationReceiptBehavior.ReceiptOperatorConfirmationReceiptBehavior ReceiptOperatorConfirmationReceiptBehavior = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setReceiptOperatorConfirmationReceiptBehavior($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Workflows\ReceiptOperatorConfirmationReceiptBehavior\ReceiptOperatorConfirmationReceiptBehavior::class);
        $this->ReceiptOperatorConfirmationReceiptBehavior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.OperatorConfirmationBehavior.OperatorConfirmationBehavior ReceiptOperatorConfirmationBehavior = 5;</code>
     * @return int
     */
    public function getReceiptOperatorConfirmationBehavior()
    {
        return isset($this->ReceiptOperatorConfirmationBehavior) ? $this->ReceiptOperatorConfirmationBehavior : 0;
    }

    public function hasReceiptOperatorConfirmationBehavior()
    {
        return isset($this->ReceiptOperatorConfirmationBehavior);
    }

    public function clearReceiptOperatorConfirmationBehavior()
    {
        unset($this->ReceiptOperatorConfirmationBehavior);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.OperatorConfirmationBehavior.OperatorConfirmationBehavior ReceiptOperatorConfirmationBehavior = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setReceiptOperatorConfirmationBehavior($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Workflows\OperatorConfirmationBehavior\OperatorConfirmationBehavior::class);
        $this->ReceiptOperatorConfirmationBehavior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.AmendmentRequestResponseBehavior.AmendmentRequestResponseBehavior AmendmentRequestResponseBehavior = 6;</code>
     * @return int
     */
    public function getAmendmentRequestResponseBehavior()
    {
        return isset($this->AmendmentRequestResponseBehavior) ? $this->AmendmentRequestResponseBehavior : 0;
    }

    public function hasAmendmentRequestResponseBehavior()
    {
        return isset($this->AmendmentRequestResponseBehavior);
    }

    public function clearAmendmentRequestResponseBehavior()
    {
        unset($this->AmendmentRequestResponseBehavior);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.AmendmentRequestResponseBehavior.AmendmentRequestResponseBehavior AmendmentRequestResponseBehavior = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setAmendmentRequestResponseBehavior($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Workflows\AmendmentRequestResponseBehavior\AmendmentRequestResponseBehavior::class);
        $this->AmendmentRequestResponseBehavior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.OperatorConfirmationBehavior.OperatorConfirmationBehavior AmendmentRequestOperatorConfirmationBehavior = 7;</code>
     * @return int
     */
    public function getAmendmentRequestOperatorConfirmationBehavior()
    {
        return isset($this->AmendmentRequestOperatorConfirmationBehavior) ? $this->AmendmentRequestOperatorConfirmationBehavior : 0;
    }

    public function hasAmendmentRequestOperatorConfirmationBehavior()
    {
        return isset($this->AmendmentRequestOperatorConfirmationBehavior);
    }

    public function clearAmendmentRequestOperatorConfirmationBehavior()
    {
        unset($this->AmendmentRequestOperatorConfirmationBehavior);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.OperatorConfirmationBehavior.OperatorConfirmationBehavior AmendmentRequestOperatorConfirmationBehavior = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setAmendmentRequestOperatorConfirmationBehavior($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Workflows\OperatorConfirmationBehavior\OperatorConfirmationBehavior::class);
        $this->AmendmentRequestOperatorConfirmationBehavior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.RoamingConfirmationBehavior.RoamingConfirmationBehavior ReceiptRoamingConfirmationBehavior = 8;</code>
     * @return int
     */
    public function getReceiptRoamingConfirmationBehavior()
    {
        return isset($this->ReceiptRoamingConfirmationBehavior) ? $this->ReceiptRoamingConfirmationBehavior : 0;
    }

    public function hasReceiptRoamingConfirmationBehavior()
    {
        return isset($this->ReceiptRoamingConfirmationBehavior);
    }

    public function clearReceiptRoamingConfirmationBehavior()
    {
        unset($this->ReceiptRoamingConfirmationBehavior);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.RoamingConfirmationBehavior.RoamingConfirmationBehavior ReceiptRoamingConfirmationBehavior = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setReceiptRoamingConfirmationBehavior($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Workflows\RoamingConfirmationBehavior\RoamingConfirmationBehavior::class);
        $this->ReceiptRoamingConfirmationBehavior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.RoamingConfirmationBehavior.RoamingConfirmationBehavior AmendmentRequestRoamingConfirmationBehavior = 9;</code>
     * @return int
     */
    public function getAmendmentRequestRoamingConfirmationBehavior()
    {
        return isset($this->AmendmentRequestRoamingConfirmationBehavior) ? $this->AmendmentRequestRoamingConfirmationBehavior : 0;
    }

    public function hasAmendmentRequestRoamingConfirmationBehavior()
    {
        return isset($this->AmendmentRequestRoamingConfirmationBehavior);
    }

    public function clearAmendmentRequestRoamingConfirmationBehavior()
    {
        unset($this->AmendmentRequestRoamingConfirmationBehavior);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.RoamingConfirmationBehavior.RoamingConfirmationBehavior AmendmentRequestRoamingConfirmationBehavior = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setAmendmentRequestRoamingConfirmationBehavior($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Workflows\RoamingConfirmationBehavior\RoamingConfirmationBehavior::class);
        $this->AmendmentRequestRoamingConfirmationBehavior = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.InvitationBehavior.InvitationBehavior InvitationBehavior = 10;</code>
     * @return int
     */
    public function getInvitationBehavior()
    {
        return isset($this->InvitationBehavior) ? $this->InvitationBehavior : 0;
    }

    public function hasInvitationBehavior()
    {
        return isset($this->InvitationBehavior);
    }

    public function clearInvitationBehavior()
    {
        unset($this->InvitationBehavior);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Workflows.InvitationBehavior.InvitationBehavior InvitationBehavior = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setInvitationBehavior($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Workflows\InvitationBehavior\InvitationBehavior::class);
        $this->InvitationBehavior = $var;

        return $this;
    }

}

