<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/ExtendedSigner.proto

namespace Diadoc\Api\Proto\Invoicing\Signers;

use UnexpectedValueException;

/**
 * Protobuf type <code>Diadoc.Api.Proto.Invoicing.Signers.SignerStatus</code>
 */
class SignerStatus
{
    /**
     * Не указано
     *
     * Generated from protobuf enum <code>SignerStatusUnspecified = 0;</code>
     */
    const SignerStatusUnspecified = 0;
    /**
     * Работник организации продавца товаров (работ, услуг, имущественных прав);
     *
     * Generated from protobuf enum <code>SellerEmployee = 1;</code>
     */
    const SellerEmployee = 1;
    /**
     * Работник организации - составителя информации продавца;
     *
     * Generated from protobuf enum <code>InformationCreatorEmployee = 2;</code>
     */
    const InformationCreatorEmployee = 2;
    /**
     * Работник иной уполномоченной организации;
     *
     * Generated from protobuf enum <code>OtherOrganizationEmployee = 3;</code>
     */
    const OtherOrganizationEmployee = 3;
    /**
     * Уполномоченное физическое лицо (в том числе индивидуальный предприниматель);
     *
     * Generated from protobuf enum <code>AuthorizedPerson = 4;</code>
     */
    const AuthorizedPerson = 4;
    /**
     * Работник организации - покупателя (для документов в формате приказа №820);
     *
     * Generated from protobuf enum <code>BuyerEmployee = 5;</code>
     */
    const BuyerEmployee = 5;
    /**
     * Работник организации - составителя файла обмена информации покупателя, если составитель файла обмена информации покупателя не является покупателем (для документов в формате приказа №820)
     *
     * Generated from protobuf enum <code>InformationCreatorBuyerEmployee = 6;</code>
     */
    const InformationCreatorBuyerEmployee = 6;

    private static $valueToName = [
        self::SignerStatusUnspecified => 'SignerStatusUnspecified',
        self::SellerEmployee => 'SellerEmployee',
        self::InformationCreatorEmployee => 'InformationCreatorEmployee',
        self::OtherOrganizationEmployee => 'OtherOrganizationEmployee',
        self::AuthorizedPerson => 'AuthorizedPerson',
        self::BuyerEmployee => 'BuyerEmployee',
        self::InformationCreatorBuyerEmployee => 'InformationCreatorBuyerEmployee',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

