<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Documents/DetectTitleResponse.proto

namespace GPBMetadata\Documents;

class DetectTitleResponse
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Events\DiadocMessagePostApi::initOnce();
        $pool->internalAddGeneratedFile(
            '
Ê
#Documents/DetectTitleResponse.protoDiadoc.Api.Proto.Documents"`
DetectTitleResponseI
DocumentTitles (21.Diadoc.Api.Proto.Documents.DetectedDocumentTitle"œ
DetectedDocumentTitle
TypeNamedId (	
Function (	
Version (	

TitleIndex (7
Metadata (2%.Diadoc.Api.Proto.Events.MetadataItembproto3'
        , true);

        static::$is_initialized = true;
    }
}

