<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/DocumentInfo.proto

namespace Diadoc\Api\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.BasicDocumentInfo</code>
 */
class BasicDocumentInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Total = 1;</code>
     */
    protected $Total = null;
    /**
     * Generated from protobuf field <code>optional bool NoVat = 2;</code>
     */
    protected $NoVat = null;
    /**
     * Generated from protobuf field <code>optional string Vat = 3;</code>
     */
    protected $Vat = null;
    /**
     * Generated from protobuf field <code>optional string Grounds = 4;</code>
     */
    protected $Grounds = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.DocumentDateAndNumber RevisionDateAndNumber = 5;</code>
     */
    protected $RevisionDateAndNumber = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Total
     *     @type bool $NoVat
     *     @type string $Vat
     *     @type string $Grounds
     *     @type \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $RevisionDateAndNumber
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\DocumentInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Total = 1;</code>
     * @return string
     */
    public function getTotal()
    {
        return isset($this->Total) ? $this->Total : '';
    }

    public function hasTotal()
    {
        return isset($this->Total);
    }

    public function clearTotal()
    {
        unset($this->Total);
    }

    /**
     * Generated from protobuf field <code>optional string Total = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->Total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional bool NoVat = 2;</code>
     * @return bool
     */
    public function getNoVat()
    {
        return isset($this->NoVat) ? $this->NoVat : false;
    }

    public function hasNoVat()
    {
        return isset($this->NoVat);
    }

    public function clearNoVat()
    {
        unset($this->NoVat);
    }

    /**
     * Generated from protobuf field <code>optional bool NoVat = 2;</code>
     * @param bool $var
     * @return $this
     */
    public function setNoVat($var)
    {
        GPBUtil::checkBool($var);
        $this->NoVat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Vat = 3;</code>
     * @return string
     */
    public function getVat()
    {
        return isset($this->Vat) ? $this->Vat : '';
    }

    public function hasVat()
    {
        return isset($this->Vat);
    }

    public function clearVat()
    {
        unset($this->Vat);
    }

    /**
     * Generated from protobuf field <code>optional string Vat = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setVat($var)
    {
        GPBUtil::checkString($var, True);
        $this->Vat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Grounds = 4;</code>
     * @return string
     */
    public function getGrounds()
    {
        return isset($this->Grounds) ? $this->Grounds : '';
    }

    public function hasGrounds()
    {
        return isset($this->Grounds);
    }

    public function clearGrounds()
    {
        unset($this->Grounds);
    }

    /**
     * Generated from protobuf field <code>optional string Grounds = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGrounds($var)
    {
        GPBUtil::checkString($var, True);
        $this->Grounds = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.DocumentDateAndNumber RevisionDateAndNumber = 5;</code>
     * @return \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber|null
     */
    public function getRevisionDateAndNumber()
    {
        return $this->RevisionDateAndNumber;
    }

    public function hasRevisionDateAndNumber()
    {
        return isset($this->RevisionDateAndNumber);
    }

    public function clearRevisionDateAndNumber()
    {
        unset($this->RevisionDateAndNumber);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.DocumentDateAndNumber RevisionDateAndNumber = 5;</code>
     * @param \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $var
     * @return $this
     */
    public function setRevisionDateAndNumber($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber::class);
        $this->RevisionDateAndNumber = $var;

        return $this;
    }

}

