<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/DocflowV3.proto

namespace Diadoc\Api\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.ConfirmationDocflow</code>
 */
class ConfirmationDocflow extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>bool IsFinished = 1;</code>
     */
    protected $IsFinished = false;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachmentV3 ConfirmationAttachment = 2;</code>
     */
    protected $ConfirmationAttachment = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp ConfirmedAt = 3;</code>
     */
    protected $ConfirmedAt = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ReceiptDocflowV3 Receipt = 4;</code>
     */
    protected $Receipt = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.OperatorConfirmationDocflow RoamingConfirmation = 5;</code>
     */
    protected $RoamingConfirmation = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $IsFinished
     *     @type \Diadoc\Api\Proto\Docflow\SignedAttachmentV3 $ConfirmationAttachment
     *     @type \Diadoc\Api\Proto\Timestamp $ConfirmedAt
     *     @type \Diadoc\Api\Proto\Docflow\ReceiptDocflowV3 $Receipt
     *     @type \Diadoc\Api\Proto\Docflow\OperatorConfirmationDocflow $RoamingConfirmation
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\DocflowV3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>bool IsFinished = 1;</code>
     * @return bool
     */
    public function getIsFinished()
    {
        return $this->IsFinished;
    }

    /**
     * Generated from protobuf field <code>bool IsFinished = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFinished($var)
    {
        GPBUtil::checkBool($var);
        $this->IsFinished = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachmentV3 ConfirmationAttachment = 2;</code>
     * @return \Diadoc\Api\Proto\Docflow\SignedAttachmentV3|null
     */
    public function getConfirmationAttachment()
    {
        return $this->ConfirmationAttachment;
    }

    public function hasConfirmationAttachment()
    {
        return isset($this->ConfirmationAttachment);
    }

    public function clearConfirmationAttachment()
    {
        unset($this->ConfirmationAttachment);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachmentV3 ConfirmationAttachment = 2;</code>
     * @param \Diadoc\Api\Proto\Docflow\SignedAttachmentV3 $var
     * @return $this
     */
    public function setConfirmationAttachment($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\SignedAttachmentV3::class);
        $this->ConfirmationAttachment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp ConfirmedAt = 3;</code>
     * @return \Diadoc\Api\Proto\Timestamp|null
     */
    public function getConfirmedAt()
    {
        return $this->ConfirmedAt;
    }

    public function hasConfirmedAt()
    {
        return isset($this->ConfirmedAt);
    }

    public function clearConfirmedAt()
    {
        unset($this->ConfirmedAt);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp ConfirmedAt = 3;</code>
     * @param \Diadoc\Api\Proto\Timestamp $var
     * @return $this
     */
    public function setConfirmedAt($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Timestamp::class);
        $this->ConfirmedAt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ReceiptDocflowV3 Receipt = 4;</code>
     * @return \Diadoc\Api\Proto\Docflow\ReceiptDocflowV3|null
     */
    public function getReceipt()
    {
        return $this->Receipt;
    }

    public function hasReceipt()
    {
        return isset($this->Receipt);
    }

    public function clearReceipt()
    {
        unset($this->Receipt);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ReceiptDocflowV3 Receipt = 4;</code>
     * @param \Diadoc\Api\Proto\Docflow\ReceiptDocflowV3 $var
     * @return $this
     */
    public function setReceipt($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\ReceiptDocflowV3::class);
        $this->Receipt = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.OperatorConfirmationDocflow RoamingConfirmation = 5;</code>
     * @return \Diadoc\Api\Proto\Docflow\OperatorConfirmationDocflow|null
     */
    public function getRoamingConfirmation()
    {
        return $this->RoamingConfirmation;
    }

    public function hasRoamingConfirmation()
    {
        return isset($this->RoamingConfirmation);
    }

    public function clearRoamingConfirmation()
    {
        unset($this->RoamingConfirmation);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.OperatorConfirmationDocflow RoamingConfirmation = 5;</code>
     * @param \Diadoc\Api\Proto\Docflow\OperatorConfirmationDocflow $var
     * @return $this
     */
    public function setRoamingConfirmation($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\OperatorConfirmationDocflow::class);
        $this->RoamingConfirmation = $var;

        return $this;
    }

}

