<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/DocumentInfoV3.proto

namespace Diadoc\Api\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.DocumentLinks</code>
 */
class DocumentLinks extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId InitialIds = 1;</code>
     */
    private $InitialIds;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId SubordinateIds = 2;</code>
     */
    private $SubordinateIds;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Diadoc\Api\Proto\DocumentId>|\Google\Protobuf\Internal\RepeatedField $InitialIds
     *     @type array<\Diadoc\Api\Proto\DocumentId>|\Google\Protobuf\Internal\RepeatedField $SubordinateIds
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\DocumentInfoV3::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId InitialIds = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInitialIds()
    {
        return $this->InitialIds;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId InitialIds = 1;</code>
     * @param array<\Diadoc\Api\Proto\DocumentId>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInitialIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\DocumentId::class);
        $this->InitialIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId SubordinateIds = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubordinateIds()
    {
        return $this->SubordinateIds;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId SubordinateIds = 2;</code>
     * @param array<\Diadoc\Api\Proto\DocumentId>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubordinateIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\DocumentId::class);
        $this->SubordinateIds = $arr;

        return $this;
    }

}

