<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/DocumentWithDocflow.proto

namespace Diadoc\Api\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.DocumentWithDocflow</code>
 */
class DocumentWithDocflow extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
     */
    protected $DocumentId = null;
    /**
     * Generated from protobuf field <code>optional string LastEventId = 2;</code>
     */
    protected $LastEventId = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp LastEventTimestamp = 3;</code>
     */
    protected $LastEventTimestamp = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.DocumentInfo DocumentInfo = 4;</code>
     */
    protected $DocumentInfo = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.Docflow Docflow = 5;</code>
     */
    protected $Docflow = null;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId InitialDocumentIds = 6;</code>
     */
    private $InitialDocumentIds;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId SubordinateDocumentIds = 7;</code>
     */
    private $SubordinateDocumentIds;
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.ForwardDocumentEvent ForwardDocumentEvents = 8;</code>
     */
    private $ForwardDocumentEvents;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Api\Proto\DocumentId $DocumentId
     *     @type string $LastEventId
     *     @type \Diadoc\Api\Proto\Timestamp $LastEventTimestamp
     *     @type \Diadoc\Api\Proto\Docflow\DocumentInfo $DocumentInfo
     *     @type \Diadoc\Api\Proto\Docflow\Docflow $Docflow
     *     @type array<\Diadoc\Api\Proto\DocumentId>|\Google\Protobuf\Internal\RepeatedField $InitialDocumentIds
     *     @type array<\Diadoc\Api\Proto\DocumentId>|\Google\Protobuf\Internal\RepeatedField $SubordinateDocumentIds
     *     @type array<\Diadoc\Api\Proto\ForwardDocumentEvent>|\Google\Protobuf\Internal\RepeatedField $ForwardDocumentEvents
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\DocumentWithDocflow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
     * @return \Diadoc\Api\Proto\DocumentId|null
     */
    public function getDocumentId()
    {
        return $this->DocumentId;
    }

    public function hasDocumentId()
    {
        return isset($this->DocumentId);
    }

    public function clearDocumentId()
    {
        unset($this->DocumentId);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.DocumentId DocumentId = 1;</code>
     * @param \Diadoc\Api\Proto\DocumentId $var
     * @return $this
     */
    public function setDocumentId($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\DocumentId::class);
        $this->DocumentId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string LastEventId = 2;</code>
     * @return string
     */
    public function getLastEventId()
    {
        return isset($this->LastEventId) ? $this->LastEventId : '';
    }

    public function hasLastEventId()
    {
        return isset($this->LastEventId);
    }

    public function clearLastEventId()
    {
        unset($this->LastEventId);
    }

    /**
     * Generated from protobuf field <code>optional string LastEventId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLastEventId($var)
    {
        GPBUtil::checkString($var, True);
        $this->LastEventId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp LastEventTimestamp = 3;</code>
     * @return \Diadoc\Api\Proto\Timestamp|null
     */
    public function getLastEventTimestamp()
    {
        return $this->LastEventTimestamp;
    }

    public function hasLastEventTimestamp()
    {
        return isset($this->LastEventTimestamp);
    }

    public function clearLastEventTimestamp()
    {
        unset($this->LastEventTimestamp);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp LastEventTimestamp = 3;</code>
     * @param \Diadoc\Api\Proto\Timestamp $var
     * @return $this
     */
    public function setLastEventTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Timestamp::class);
        $this->LastEventTimestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.DocumentInfo DocumentInfo = 4;</code>
     * @return \Diadoc\Api\Proto\Docflow\DocumentInfo|null
     */
    public function getDocumentInfo()
    {
        return $this->DocumentInfo;
    }

    public function hasDocumentInfo()
    {
        return isset($this->DocumentInfo);
    }

    public function clearDocumentInfo()
    {
        unset($this->DocumentInfo);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.DocumentInfo DocumentInfo = 4;</code>
     * @param \Diadoc\Api\Proto\Docflow\DocumentInfo $var
     * @return $this
     */
    public function setDocumentInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\DocumentInfo::class);
        $this->DocumentInfo = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.Docflow Docflow = 5;</code>
     * @return \Diadoc\Api\Proto\Docflow\Docflow|null
     */
    public function getDocflow()
    {
        return $this->Docflow;
    }

    public function hasDocflow()
    {
        return isset($this->Docflow);
    }

    public function clearDocflow()
    {
        unset($this->Docflow);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.Docflow Docflow = 5;</code>
     * @param \Diadoc\Api\Proto\Docflow\Docflow $var
     * @return $this
     */
    public function setDocflow($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\Docflow::class);
        $this->Docflow = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId InitialDocumentIds = 6;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getInitialDocumentIds()
    {
        return $this->InitialDocumentIds;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId InitialDocumentIds = 6;</code>
     * @param array<\Diadoc\Api\Proto\DocumentId>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setInitialDocumentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\DocumentId::class);
        $this->InitialDocumentIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId SubordinateDocumentIds = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSubordinateDocumentIds()
    {
        return $this->SubordinateDocumentIds;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.DocumentId SubordinateDocumentIds = 7;</code>
     * @param array<\Diadoc\Api\Proto\DocumentId>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSubordinateDocumentIds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\DocumentId::class);
        $this->SubordinateDocumentIds = $arr;

        return $this;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.ForwardDocumentEvent ForwardDocumentEvents = 8;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getForwardDocumentEvents()
    {
        return $this->ForwardDocumentEvents;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.ForwardDocumentEvent ForwardDocumentEvents = 8;</code>
     * @param array<\Diadoc\Api\Proto\ForwardDocumentEvent>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setForwardDocumentEvents($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\ForwardDocumentEvent::class);
        $this->ForwardDocumentEvents = $arr;

        return $this;
    }

}

