<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/Attachment.proto

namespace Diadoc\Api\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.Entity</code>
 */
class Entity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string EntityId = 1;</code>
     */
    protected $EntityId = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp CreationTimestamp = 2;</code>
     */
    protected $CreationTimestamp = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Content Content = 3;</code>
     */
    protected $Content = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $EntityId
     *     @type \Diadoc\Api\Proto\Timestamp $CreationTimestamp
     *     @type \Diadoc\Api\Proto\Content $Content
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\Attachment::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string EntityId = 1;</code>
     * @return string
     */
    public function getEntityId()
    {
        return isset($this->EntityId) ? $this->EntityId : '';
    }

    public function hasEntityId()
    {
        return isset($this->EntityId);
    }

    public function clearEntityId()
    {
        unset($this->EntityId);
    }

    /**
     * Generated from protobuf field <code>optional string EntityId = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEntityId($var)
    {
        GPBUtil::checkString($var, True);
        $this->EntityId = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp CreationTimestamp = 2;</code>
     * @return \Diadoc\Api\Proto\Timestamp|null
     */
    public function getCreationTimestamp()
    {
        return $this->CreationTimestamp;
    }

    public function hasCreationTimestamp()
    {
        return isset($this->CreationTimestamp);
    }

    public function clearCreationTimestamp()
    {
        unset($this->CreationTimestamp);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp CreationTimestamp = 2;</code>
     * @param \Diadoc\Api\Proto\Timestamp $var
     * @return $this
     */
    public function setCreationTimestamp($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Timestamp::class);
        $this->CreationTimestamp = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Content Content = 3;</code>
     * @return \Diadoc\Api\Proto\Content|null
     */
    public function getContent()
    {
        return $this->Content;
    }

    public function hasContent()
    {
        return isset($this->Content);
    }

    public function clearContent()
    {
        unset($this->Content);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Content Content = 3;</code>
     * @param \Diadoc\Api\Proto\Content $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Content::class);
        $this->Content = $var;

        return $this;
    }

}

