<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/InvoiceDocflow.proto

namespace Diadoc\Api\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.InboundInvoiceReceiptDocflow</code>
 */
class InboundInvoiceReceiptDocflow extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool IsFinished = 1;</code>
     */
    protected $IsFinished = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachment ReceiptAttachment = 2;</code>
     */
    protected $ReceiptAttachment = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.InvoiceConfirmationDocflow ConfirmationDocflow = 3;</code>
     */
    protected $ConfirmationDocflow = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $IsFinished
     *     @type \Diadoc\Api\Proto\Docflow\SignedAttachment $ReceiptAttachment
     *     @type \Diadoc\Api\Proto\Docflow\InvoiceConfirmationDocflow $ConfirmationDocflow
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\InvoiceDocflow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool IsFinished = 1;</code>
     * @return bool
     */
    public function getIsFinished()
    {
        return isset($this->IsFinished) ? $this->IsFinished : false;
    }

    public function hasIsFinished()
    {
        return isset($this->IsFinished);
    }

    public function clearIsFinished()
    {
        unset($this->IsFinished);
    }

    /**
     * Generated from protobuf field <code>optional bool IsFinished = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFinished($var)
    {
        GPBUtil::checkBool($var);
        $this->IsFinished = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachment ReceiptAttachment = 2;</code>
     * @return \Diadoc\Api\Proto\Docflow\SignedAttachment|null
     */
    public function getReceiptAttachment()
    {
        return $this->ReceiptAttachment;
    }

    public function hasReceiptAttachment()
    {
        return isset($this->ReceiptAttachment);
    }

    public function clearReceiptAttachment()
    {
        unset($this->ReceiptAttachment);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachment ReceiptAttachment = 2;</code>
     * @param \Diadoc\Api\Proto\Docflow\SignedAttachment $var
     * @return $this
     */
    public function setReceiptAttachment($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\SignedAttachment::class);
        $this->ReceiptAttachment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.InvoiceConfirmationDocflow ConfirmationDocflow = 3;</code>
     * @return \Diadoc\Api\Proto\Docflow\InvoiceConfirmationDocflow|null
     */
    public function getConfirmationDocflow()
    {
        return $this->ConfirmationDocflow;
    }

    public function hasConfirmationDocflow()
    {
        return isset($this->ConfirmationDocflow);
    }

    public function clearConfirmationDocflow()
    {
        unset($this->ConfirmationDocflow);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.InvoiceConfirmationDocflow ConfirmationDocflow = 3;</code>
     * @param \Diadoc\Api\Proto\Docflow\InvoiceConfirmationDocflow $var
     * @return $this
     */
    public function setConfirmationDocflow($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\InvoiceConfirmationDocflow::class);
        $this->ConfirmationDocflow = $var;

        return $this;
    }

}

