<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/InvoiceDocflow.proto

namespace Diadoc\Api\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.InvoiceCorrectionRequestDocflow</code>
 */
class InvoiceCorrectionRequestDocflow extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional bool IsFinished = 1;</code>
     */
    protected $IsFinished = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachment CorrectionRequestAttachment = 2;</code>
     */
    protected $CorrectionRequestAttachment = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ReceiptDocflow ReceiptDocflow = 3;</code>
     */
    protected $ReceiptDocflow = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type bool $IsFinished
     *     @type \Diadoc\Api\Proto\Docflow\SignedAttachment $CorrectionRequestAttachment
     *     @type \Diadoc\Api\Proto\Docflow\ReceiptDocflow $ReceiptDocflow
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\InvoiceDocflow::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional bool IsFinished = 1;</code>
     * @return bool
     */
    public function getIsFinished()
    {
        return isset($this->IsFinished) ? $this->IsFinished : false;
    }

    public function hasIsFinished()
    {
        return isset($this->IsFinished);
    }

    public function clearIsFinished()
    {
        unset($this->IsFinished);
    }

    /**
     * Generated from protobuf field <code>optional bool IsFinished = 1;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsFinished($var)
    {
        GPBUtil::checkBool($var);
        $this->IsFinished = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachment CorrectionRequestAttachment = 2;</code>
     * @return \Diadoc\Api\Proto\Docflow\SignedAttachment|null
     */
    public function getCorrectionRequestAttachment()
    {
        return $this->CorrectionRequestAttachment;
    }

    public function hasCorrectionRequestAttachment()
    {
        return isset($this->CorrectionRequestAttachment);
    }

    public function clearCorrectionRequestAttachment()
    {
        unset($this->CorrectionRequestAttachment);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.SignedAttachment CorrectionRequestAttachment = 2;</code>
     * @param \Diadoc\Api\Proto\Docflow\SignedAttachment $var
     * @return $this
     */
    public function setCorrectionRequestAttachment($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\SignedAttachment::class);
        $this->CorrectionRequestAttachment = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ReceiptDocflow ReceiptDocflow = 3;</code>
     * @return \Diadoc\Api\Proto\Docflow\ReceiptDocflow|null
     */
    public function getReceiptDocflow()
    {
        return $this->ReceiptDocflow;
    }

    public function hasReceiptDocflow()
    {
        return isset($this->ReceiptDocflow);
    }

    public function clearReceiptDocflow()
    {
        unset($this->ReceiptDocflow);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.ReceiptDocflow ReceiptDocflow = 3;</code>
     * @param \Diadoc\Api\Proto\Docflow\ReceiptDocflow $var
     * @return $this
     */
    public function setReceiptDocflow($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\ReceiptDocflow::class);
        $this->ReceiptDocflow = $var;

        return $this;
    }

}

