<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/DocumentInfo.proto

namespace Diadoc\Api\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.InvoiceDocumentInfo</code>
 */
class InvoiceDocumentInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Total = 1;</code>
     */
    protected $Total = null;
    /**
     * Generated from protobuf field <code>optional string Vat = 2;</code>
     */
    protected $Vat = null;
    /**
     * Generated from protobuf field <code>optional int32 CurrencyCode = 3;</code>
     */
    protected $CurrencyCode = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.DocumentDateAndNumber OriginalInvoiceDateAndNumber = 4;</code>
     */
    protected $OriginalInvoiceDateAndNumber = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Total
     *     @type string $Vat
     *     @type int $CurrencyCode
     *     @type \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $OriginalInvoiceDateAndNumber
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\DocumentInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Total = 1;</code>
     * @return string
     */
    public function getTotal()
    {
        return isset($this->Total) ? $this->Total : '';
    }

    public function hasTotal()
    {
        return isset($this->Total);
    }

    public function clearTotal()
    {
        unset($this->Total);
    }

    /**
     * Generated from protobuf field <code>optional string Total = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->Total = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Vat = 2;</code>
     * @return string
     */
    public function getVat()
    {
        return isset($this->Vat) ? $this->Vat : '';
    }

    public function hasVat()
    {
        return isset($this->Vat);
    }

    public function clearVat()
    {
        unset($this->Vat);
    }

    /**
     * Generated from protobuf field <code>optional string Vat = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setVat($var)
    {
        GPBUtil::checkString($var, True);
        $this->Vat = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional int32 CurrencyCode = 3;</code>
     * @return int
     */
    public function getCurrencyCode()
    {
        return isset($this->CurrencyCode) ? $this->CurrencyCode : 0;
    }

    public function hasCurrencyCode()
    {
        return isset($this->CurrencyCode);
    }

    public function clearCurrencyCode()
    {
        unset($this->CurrencyCode);
    }

    /**
     * Generated from protobuf field <code>optional int32 CurrencyCode = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setCurrencyCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->CurrencyCode = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.DocumentDateAndNumber OriginalInvoiceDateAndNumber = 4;</code>
     * @return \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber|null
     */
    public function getOriginalInvoiceDateAndNumber()
    {
        return $this->OriginalInvoiceDateAndNumber;
    }

    public function hasOriginalInvoiceDateAndNumber()
    {
        return isset($this->OriginalInvoiceDateAndNumber);
    }

    public function clearOriginalInvoiceDateAndNumber()
    {
        unset($this->OriginalInvoiceDateAndNumber);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Docflow.DocumentDateAndNumber OriginalInvoiceDateAndNumber = 4;</code>
     * @param \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $var
     * @return $this
     */
    public function setOriginalInvoiceDateAndNumber($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber::class);
        $this->OriginalInvoiceDateAndNumber = $var;

        return $this;
    }

}

