<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Docflow/DocumentInfo.proto

namespace Diadoc\Api\Proto\Docflow;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Docflow.SupplementaryAgreementDocumentInfo</code>
 */
class SupplementaryAgreementDocumentInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string ContractType = 1;</code>
     */
    protected $ContractType = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Docflow.DocumentDateAndNumber ContractDocumentDateAndNumber = 2;</code>
     */
    protected $ContractDocumentDateAndNumber = null;
    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Docflow.DocumentDateAndNumber DocumentDateAndNumber = 3;</code>
     */
    protected $DocumentDateAndNumber = null;
    /**
     * Generated from protobuf field <code>optional string Total = 4;</code>
     */
    protected $Total = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $ContractType
     *     @type \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $ContractDocumentDateAndNumber
     *     @type \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $DocumentDateAndNumber
     *     @type string $Total
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Docflow\DocumentInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string ContractType = 1;</code>
     * @return string
     */
    public function getContractType()
    {
        return isset($this->ContractType) ? $this->ContractType : '';
    }

    public function hasContractType()
    {
        return isset($this->ContractType);
    }

    public function clearContractType()
    {
        unset($this->ContractType);
    }

    /**
     * Generated from protobuf field <code>optional string ContractType = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setContractType($var)
    {
        GPBUtil::checkString($var, True);
        $this->ContractType = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Docflow.DocumentDateAndNumber ContractDocumentDateAndNumber = 2;</code>
     * @return \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber|null
     */
    public function getContractDocumentDateAndNumber()
    {
        return $this->ContractDocumentDateAndNumber;
    }

    public function hasContractDocumentDateAndNumber()
    {
        return isset($this->ContractDocumentDateAndNumber);
    }

    public function clearContractDocumentDateAndNumber()
    {
        unset($this->ContractDocumentDateAndNumber);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Docflow.DocumentDateAndNumber ContractDocumentDateAndNumber = 2;</code>
     * @param \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $var
     * @return $this
     */
    public function setContractDocumentDateAndNumber($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber::class);
        $this->ContractDocumentDateAndNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Docflow.DocumentDateAndNumber DocumentDateAndNumber = 3;</code>
     * @return \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber|null
     */
    public function getDocumentDateAndNumber()
    {
        return $this->DocumentDateAndNumber;
    }

    public function hasDocumentDateAndNumber()
    {
        return isset($this->DocumentDateAndNumber);
    }

    public function clearDocumentDateAndNumber()
    {
        unset($this->DocumentDateAndNumber);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Docflow.DocumentDateAndNumber DocumentDateAndNumber = 3;</code>
     * @param \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber $var
     * @return $this
     */
    public function setDocumentDateAndNumber($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Docflow\DocumentDateAndNumber::class);
        $this->DocumentDateAndNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string Total = 4;</code>
     * @return string
     */
    public function getTotal()
    {
        return isset($this->Total) ? $this->Total : '';
    }

    public function hasTotal()
    {
        return isset($this->Total);
    }

    public function clearTotal()
    {
        unset($this->Total);
    }

    /**
     * Generated from protobuf field <code>optional string Total = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTotal($var)
    {
        GPBUtil::checkString($var, True);
        $this->Total = $var;

        return $this;
    }

}

