<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: KeyValueStorage/KeyValueStorage.proto

namespace GPBMetadata\KeyValueStorage;

class KeyValueStorage
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(
            '
†
%KeyValueStorage/KeyValueStorage.proto Diadoc.Api.Proto.KeyValueStorage"2
KeyValueStorageEntry
Key (	
Value (	",
KeyValueStorageApiGetRequest
Keys (	"h
KeyValueStorageApiGetResponseG
Entries (26.Diadoc.Api.Proto.KeyValueStorage.KeyValueStorageEntry"g
KeyValueStorageApiPutRequestG
Entries (26.Diadoc.Api.Proto.KeyValueStorage.KeyValueStorageEntrybproto3'
        , true);

        static::$is_initialized = true;
    }
}

