<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Departments/DepartmentList.proto

namespace GPBMetadata\Departments;

class DepartmentList
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\Departments\Department::initOnce();
        $pool->internalAddGeneratedFile(
            '
­
 Departments/DepartmentList.protoDiadoc.Api.Proto.Departments"c
DepartmentList=
Departments (2(.Diadoc.Api.Proto.Departments.Department

TotalCount (bproto3'
        , true);

        static::$is_initialized = true;
    }
}

