<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PowersOfAttorney/PowerOfAttorneyValidation.proto

namespace Diadoc\Api\Proto\PowersOfAttorney;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.PowersOfAttorney.ConfidantCertificateToPrevalidate</code>
 */
class ConfidantCertificateToPrevalidate extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>optional string Thumbprint = 1;</code>
     */
    protected $Thumbprint = null;
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Content_v3 Content = 2;</code>
     */
    protected $Content = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Thumbprint
     *     @type \Diadoc\Api\Proto\Content_v3 $Content
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PowersOfAttorney\PowerOfAttorneyValidation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>optional string Thumbprint = 1;</code>
     * @return string
     */
    public function getThumbprint()
    {
        return isset($this->Thumbprint) ? $this->Thumbprint : '';
    }

    public function hasThumbprint()
    {
        return isset($this->Thumbprint);
    }

    public function clearThumbprint()
    {
        unset($this->Thumbprint);
    }

    /**
     * Generated from protobuf field <code>optional string Thumbprint = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setThumbprint($var)
    {
        GPBUtil::checkString($var, True);
        $this->Thumbprint = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Content_v3 Content = 2;</code>
     * @return \Diadoc\Api\Proto\Content_v3|null
     */
    public function getContent()
    {
        return $this->Content;
    }

    public function hasContent()
    {
        return isset($this->Content);
    }

    public function clearContent()
    {
        unset($this->Content);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Content_v3 Content = 2;</code>
     * @param \Diadoc\Api\Proto\Content_v3 $var
     * @return $this
     */
    public function setContent($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Content_v3::class);
        $this->Content = $var;

        return $this;
    }

}

