<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PowersOfAttorney/PowerOfAttorneyValidation.proto

namespace Diadoc\Api\Proto\PowersOfAttorney;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyPrevalidateRequest</code>
 */
class PowerOfAttorneyPrevalidateRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.PowersOfAttorney.ConfidantCertificateToPrevalidate ConfidantCertificate = 1;</code>
     */
    protected $ConfidantCertificate = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Api\Proto\PowersOfAttorney\ConfidantCertificateToPrevalidate $ConfidantCertificate
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PowersOfAttorney\PowerOfAttorneyValidation::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.PowersOfAttorney.ConfidantCertificateToPrevalidate ConfidantCertificate = 1;</code>
     * @return \Diadoc\Api\Proto\PowersOfAttorney\ConfidantCertificateToPrevalidate|null
     */
    public function getConfidantCertificate()
    {
        return $this->ConfidantCertificate;
    }

    public function hasConfidantCertificate()
    {
        return isset($this->ConfidantCertificate);
    }

    public function clearConfidantCertificate()
    {
        unset($this->ConfidantCertificate);
    }

    /**
     * Generated from protobuf field <code>.Diadoc.Api.Proto.PowersOfAttorney.ConfidantCertificateToPrevalidate ConfidantCertificate = 1;</code>
     * @param \Diadoc\Api\Proto\PowersOfAttorney\ConfidantCertificateToPrevalidate $var
     * @return $this
     */
    public function setConfidantCertificate($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\PowersOfAttorney\ConfidantCertificateToPrevalidate::class);
        $this->ConfidantCertificate = $var;

        return $this;
    }

}

