<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PowersOfAttorney/PowerOfAttorney.proto

namespace Diadoc\Api\Proto\PowersOfAttorney;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyIssuerPhysicalEntity</code>
 */
class PowerOfAttorneyIssuerPhysicalEntity extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Inn = 1;</code>
     */
    protected $Inn = '';
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.FullName PersonName = 2;</code>
     */
    protected $PersonName = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Inn
     *     @type \Diadoc\Api\Proto\FullName $PersonName
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PowersOfAttorney\PowerOfAttorney::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Inn = 1;</code>
     * @return string
     */
    public function getInn()
    {
        return $this->Inn;
    }

    /**
     * Generated from protobuf field <code>string Inn = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInn($var)
    {
        GPBUtil::checkString($var, True);
        $this->Inn = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.FullName PersonName = 2;</code>
     * @return \Diadoc\Api\Proto\FullName|null
     */
    public function getPersonName()
    {
        return $this->PersonName;
    }

    public function hasPersonName()
    {
        return isset($this->PersonName);
    }

    public function clearPersonName()
    {
        unset($this->PersonName);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.FullName PersonName = 2;</code>
     * @param \Diadoc\Api\Proto\FullName $var
     * @return $this
     */
    public function setPersonName($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\FullName::class);
        $this->PersonName = $var;

        return $this;
    }

}

