<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PowersOfAttorney/PowerOfAttorney.proto

namespace Diadoc\Api\Proto\PowersOfAttorney;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyStatus</code>
 */
class PowerOfAttorneyStatus extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string Status = 1;</code>
     */
    protected $Status = '';
    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp LastCheckAt = 2;</code>
     */
    protected $LastCheckAt = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Status
     *     @type \Diadoc\Api\Proto\Timestamp $LastCheckAt
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PowersOfAttorney\PowerOfAttorney::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string Status = 1;</code>
     * @return string
     */
    public function getStatus()
    {
        return $this->Status;
    }

    /**
     * Generated from protobuf field <code>string Status = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkString($var, True);
        $this->Status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp LastCheckAt = 2;</code>
     * @return \Diadoc\Api\Proto\Timestamp|null
     */
    public function getLastCheckAt()
    {
        return $this->LastCheckAt;
    }

    public function hasLastCheckAt()
    {
        return isset($this->LastCheckAt);
    }

    public function clearLastCheckAt()
    {
        unset($this->LastCheckAt);
    }

    /**
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Timestamp LastCheckAt = 2;</code>
     * @param \Diadoc\Api\Proto\Timestamp $var
     * @return $this
     */
    public function setLastCheckAt($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Timestamp::class);
        $this->LastCheckAt = $var;

        return $this;
    }

}

