<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PowersOfAttorney/PowerOfAttorney.proto

namespace Diadoc\Api\Proto\PowersOfAttorney;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.PowersOfAttorney.PowerOfAttorneyDelegationInfo</code>
 */
class PowerOfAttorneyDelegationInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string RootRegistrationNumber = 1;</code>
     */
    protected $RootRegistrationNumber = '';
    /**
     * Generated from protobuf field <code>optional string ParentRegistrationNumber = 2;</code>
     */
    protected $ParentRegistrationNumber = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $RootRegistrationNumber
     *     @type string $ParentRegistrationNumber
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\PowersOfAttorney\PowerOfAttorney::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string RootRegistrationNumber = 1;</code>
     * @return string
     */
    public function getRootRegistrationNumber()
    {
        return $this->RootRegistrationNumber;
    }

    /**
     * Generated from protobuf field <code>string RootRegistrationNumber = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setRootRegistrationNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->RootRegistrationNumber = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>optional string ParentRegistrationNumber = 2;</code>
     * @return string
     */
    public function getParentRegistrationNumber()
    {
        return isset($this->ParentRegistrationNumber) ? $this->ParentRegistrationNumber : '';
    }

    public function hasParentRegistrationNumber()
    {
        return isset($this->ParentRegistrationNumber);
    }

    public function clearParentRegistrationNumber()
    {
        unset($this->ParentRegistrationNumber);
    }

    /**
     * Generated from protobuf field <code>optional string ParentRegistrationNumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setParentRegistrationNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->ParentRegistrationNumber = $var;

        return $this;
    }

}

