<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/AcceptanceCertificateInfo.proto

namespace Diadoc\Api\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Со стороны заказчика
 *
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.AcceptanceCertificateBuyerTitleInfo</code>
 */
class AcceptanceCertificateBuyerTitleInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Претензии
     *
     * Generated from protobuf field <code>optional string Complaints = 1;</code>
     */
    protected $Complaints = null;
    /**
     * Сведения о подписи акта
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.AcceptanceCertificateSignatureInfo Signature = 2;</code>
     */
    protected $Signature = null;
    /**
     * Подписант
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Signer Signer = 3;</code>
     */
    protected $Signer = null;
    /**
     * Дополнительная информация
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 4;</code>
     */
    protected $AdditionalInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $Complaints
     *           Претензии
     *     @type \Diadoc\Api\Proto\Invoicing\AcceptanceCertificateSignatureInfo $Signature
     *           Сведения о подписи акта
     *     @type \Diadoc\Api\Proto\Invoicing\Signer $Signer
     *           Подписант
     *     @type string $AdditionalInfo
     *           Дополнительная информация
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\AcceptanceCertificateInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Претензии
     *
     * Generated from protobuf field <code>optional string Complaints = 1;</code>
     * @return string
     */
    public function getComplaints()
    {
        return isset($this->Complaints) ? $this->Complaints : '';
    }

    public function hasComplaints()
    {
        return isset($this->Complaints);
    }

    public function clearComplaints()
    {
        unset($this->Complaints);
    }

    /**
     * Претензии
     *
     * Generated from protobuf field <code>optional string Complaints = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setComplaints($var)
    {
        GPBUtil::checkString($var, True);
        $this->Complaints = $var;

        return $this;
    }

    /**
     * Сведения о подписи акта
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.AcceptanceCertificateSignatureInfo Signature = 2;</code>
     * @return \Diadoc\Api\Proto\Invoicing\AcceptanceCertificateSignatureInfo|null
     */
    public function getSignature()
    {
        return $this->Signature;
    }

    public function hasSignature()
    {
        return isset($this->Signature);
    }

    public function clearSignature()
    {
        unset($this->Signature);
    }

    /**
     * Сведения о подписи акта
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.AcceptanceCertificateSignatureInfo Signature = 2;</code>
     * @param \Diadoc\Api\Proto\Invoicing\AcceptanceCertificateSignatureInfo $var
     * @return $this
     */
    public function setSignature($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\AcceptanceCertificateSignatureInfo::class);
        $this->Signature = $var;

        return $this;
    }

    /**
     * Подписант
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Signer Signer = 3;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Signer|null
     */
    public function getSigner()
    {
        return $this->Signer;
    }

    public function hasSigner()
    {
        return isset($this->Signer);
    }

    public function clearSigner()
    {
        unset($this->Signer);
    }

    /**
     * Подписант
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Signer Signer = 3;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Signer $var
     * @return $this
     */
    public function setSigner($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Signer::class);
        $this->Signer = $var;

        return $this;
    }

    /**
     * Дополнительная информация
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 4;</code>
     * @return string
     */
    public function getAdditionalInfo()
    {
        return isset($this->AdditionalInfo) ? $this->AdditionalInfo : '';
    }

    public function hasAdditionalInfo()
    {
        return isset($this->AdditionalInfo);
    }

    public function clearAdditionalInfo()
    {
        unset($this->AdditionalInfo);
    }

    /**
     * Дополнительная информация
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAdditionalInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->AdditionalInfo = $var;

        return $this;
    }

}

