<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/AcceptanceCertificate552Info.proto

namespace Diadoc\Api\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.AcceptanceCertificate552SellerTitleInfo</code>
 */
class AcceptanceCertificate552SellerTitleInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Исполнитель (продавец услуг) // Исполнитель
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Organizations.ExtendedOrganizationInfo Seller = 1;</code>
     */
    protected $Seller = null;
    /**
     * Заказчик (покупатель услуг) // Заказчик
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Organizations.ExtendedOrganizationInfo Buyer = 2;</code>
     */
    protected $Buyer = null;
    /**
     * Подписант // Документ.Подписант
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.Signers.ExtendedSigner Signers = 3;</code>
     */
    private $Signers;
    /**
     * Основание // Основание
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.GroundInfo Grounds = 4;</code>
     */
    private $Grounds;
    /**
     * Валюта (код) // КодОКВ
     *
     * Generated from protobuf field <code>string Currency = 5;</code>
     */
    protected $Currency = '';
    /**
     * Курс валюты // КурсВал
     *
     * Generated from protobuf field <code>optional string CurrencyRate = 6;</code>
     */
    protected $CurrencyRate = null;
    /**
     * Описание выполненных работ // ОписРабот
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AcceptanceCertificate552WorkDescription Works = 7;</code>
     */
    private $Works;
    /**
     * Дата составления документа о передаче товара // ИдентДок.ДатаДокПРУ
     *
     * Generated from protobuf field <code>string DocumentDate = 8;</code>
     */
    protected $DocumentDate = '';
    /**
     * Номер документа о передаче товара // ИдентДок.НомДокПРУ
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 9;</code>
     */
    protected $DocumentNumber = null;
    /**
     * Дата исправления документа // ИспрДокПРУ.ДатаИспрДокПРУ
     *
     * Generated from protobuf field <code>optional string RevisionDate = 10;</code>
     */
    protected $RevisionDate = null;
    /**
     * Номер исправления документа // ИспрДокПРУ.НомИспрДокПРУ
     *
     * Generated from protobuf field <code>optional string RevisionNumber = 11;</code>
     */
    protected $RevisionNumber = null;
    /**
     * Составитель файла информации продавца // НаимЭконСубСост
     *
     * Generated from protobuf field <code>string DocumentCreator = 12;</code>
     */
    protected $DocumentCreator = '';
    /**
     * Основание, по которому экономический субъект является составителем файла //ОснДоверОргСост
     *
     * Generated from protobuf field <code>optional string DocumentCreatorBase = 13;</code>
     */
    protected $DocumentCreatorBase = null;
    /**
     * Вид операции // ВидОперации
     *
     * Generated from protobuf field <code>optional string OperationType = 14;</code>
     */
    protected $OperationType = null;
    /**
     * Заголовок содержания операции // ЗагСодОпер
     *
     * Generated from protobuf field <code>optional string OperationTitle = 15;</code>
     */
    protected $OperationTitle = null;
    /**
     * Идентификатор государственного контракта // ИдГосКон
     *
     * Generated from protobuf field <code>optional string GovernmentContractInfo = 16;</code>
     */
    protected $GovernmentContractInfo = null;
    /**
     * Информационное поле документа // ИнфПолФХЖ1
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.AdditionalInfoId AdditionalInfoId = 17;</code>
     */
    protected $AdditionalInfoId = null;
    /**
     * Наименование первичного документа, определенное организацией // НаимДок.НаимДокОпр
     *
     * Generated from protobuf field <code>string DocumentName = 18;</code>
     */
    protected $DocumentName = '';
    /**
     * Содержание факта хозяйственной жизни - сведения о передаче результатов работ (о предъявлении оказанных услуг) // СодФХЖ2
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.AcceptanceCertificate552TransferInfo TransferInfo = 19;</code>
     */
    protected $TransferInfo = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \Diadoc\Api\Proto\Invoicing\Organizations\ExtendedOrganizationInfo $Seller
     *           Исполнитель (продавец услуг) // Исполнитель
     *     @type \Diadoc\Api\Proto\Invoicing\Organizations\ExtendedOrganizationInfo $Buyer
     *           Заказчик (покупатель услуг) // Заказчик
     *     @type array<\Diadoc\Api\Proto\Invoicing\Signers\ExtendedSigner>|\Google\Protobuf\Internal\RepeatedField $Signers
     *           Подписант // Документ.Подписант
     *     @type array<\Diadoc\Api\Proto\Invoicing\GroundInfo>|\Google\Protobuf\Internal\RepeatedField $Grounds
     *           Основание // Основание
     *     @type string $Currency
     *           Валюта (код) // КодОКВ
     *     @type string $CurrencyRate
     *           Курс валюты // КурсВал
     *     @type array<\Diadoc\Api\Proto\Invoicing\AcceptanceCertificate552WorkDescription>|\Google\Protobuf\Internal\RepeatedField $Works
     *           Описание выполненных работ // ОписРабот
     *     @type string $DocumentDate
     *           Дата составления документа о передаче товара // ИдентДок.ДатаДокПРУ
     *     @type string $DocumentNumber
     *           Номер документа о передаче товара // ИдентДок.НомДокПРУ
     *     @type string $RevisionDate
     *           Дата исправления документа // ИспрДокПРУ.ДатаИспрДокПРУ
     *     @type string $RevisionNumber
     *           Номер исправления документа // ИспрДокПРУ.НомИспрДокПРУ
     *     @type string $DocumentCreator
     *           Составитель файла информации продавца // НаимЭконСубСост
     *     @type string $DocumentCreatorBase
     *           Основание, по которому экономический субъект является составителем файла //ОснДоверОргСост
     *     @type string $OperationType
     *           Вид операции // ВидОперации
     *     @type string $OperationTitle
     *           Заголовок содержания операции // ЗагСодОпер
     *     @type string $GovernmentContractInfo
     *           Идентификатор государственного контракта // ИдГосКон
     *     @type \Diadoc\Api\Proto\Invoicing\AdditionalInfoId $AdditionalInfoId
     *           Информационное поле документа // ИнфПолФХЖ1
     *     @type string $DocumentName
     *           Наименование первичного документа, определенное организацией // НаимДок.НаимДокОпр
     *     @type \Diadoc\Api\Proto\Invoicing\AcceptanceCertificate552TransferInfo $TransferInfo
     *           Содержание факта хозяйственной жизни - сведения о передаче результатов работ (о предъявлении оказанных услуг) // СодФХЖ2
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\AcceptanceCertificate552Info::initOnce();
        parent::__construct($data);
    }

    /**
     * Исполнитель (продавец услуг) // Исполнитель
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Organizations.ExtendedOrganizationInfo Seller = 1;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Organizations\ExtendedOrganizationInfo|null
     */
    public function getSeller()
    {
        return $this->Seller;
    }

    public function hasSeller()
    {
        return isset($this->Seller);
    }

    public function clearSeller()
    {
        unset($this->Seller);
    }

    /**
     * Исполнитель (продавец услуг) // Исполнитель
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Organizations.ExtendedOrganizationInfo Seller = 1;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Organizations\ExtendedOrganizationInfo $var
     * @return $this
     */
    public function setSeller($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Organizations\ExtendedOrganizationInfo::class);
        $this->Seller = $var;

        return $this;
    }

    /**
     * Заказчик (покупатель услуг) // Заказчик
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Organizations.ExtendedOrganizationInfo Buyer = 2;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Organizations\ExtendedOrganizationInfo|null
     */
    public function getBuyer()
    {
        return $this->Buyer;
    }

    public function hasBuyer()
    {
        return isset($this->Buyer);
    }

    public function clearBuyer()
    {
        unset($this->Buyer);
    }

    /**
     * Заказчик (покупатель услуг) // Заказчик
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Organizations.ExtendedOrganizationInfo Buyer = 2;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Organizations\ExtendedOrganizationInfo $var
     * @return $this
     */
    public function setBuyer($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Organizations\ExtendedOrganizationInfo::class);
        $this->Buyer = $var;

        return $this;
    }

    /**
     * Подписант // Документ.Подписант
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.Signers.ExtendedSigner Signers = 3;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getSigners()
    {
        return $this->Signers;
    }

    /**
     * Подписант // Документ.Подписант
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.Signers.ExtendedSigner Signers = 3;</code>
     * @param array<\Diadoc\Api\Proto\Invoicing\Signers\ExtendedSigner>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setSigners($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Invoicing\Signers\ExtendedSigner::class);
        $this->Signers = $arr;

        return $this;
    }

    /**
     * Основание // Основание
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.GroundInfo Grounds = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getGrounds()
    {
        return $this->Grounds;
    }

    /**
     * Основание // Основание
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.GroundInfo Grounds = 4;</code>
     * @param array<\Diadoc\Api\Proto\Invoicing\GroundInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setGrounds($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Invoicing\GroundInfo::class);
        $this->Grounds = $arr;

        return $this;
    }

    /**
     * Валюта (код) // КодОКВ
     *
     * Generated from protobuf field <code>string Currency = 5;</code>
     * @return string
     */
    public function getCurrency()
    {
        return $this->Currency;
    }

    /**
     * Валюта (код) // КодОКВ
     *
     * Generated from protobuf field <code>string Currency = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->Currency = $var;

        return $this;
    }

    /**
     * Курс валюты // КурсВал
     *
     * Generated from protobuf field <code>optional string CurrencyRate = 6;</code>
     * @return string
     */
    public function getCurrencyRate()
    {
        return isset($this->CurrencyRate) ? $this->CurrencyRate : '';
    }

    public function hasCurrencyRate()
    {
        return isset($this->CurrencyRate);
    }

    public function clearCurrencyRate()
    {
        unset($this->CurrencyRate);
    }

    /**
     * Курс валюты // КурсВал
     *
     * Generated from protobuf field <code>optional string CurrencyRate = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrencyRate($var)
    {
        GPBUtil::checkString($var, True);
        $this->CurrencyRate = $var;

        return $this;
    }

    /**
     * Описание выполненных работ // ОписРабот
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AcceptanceCertificate552WorkDescription Works = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWorks()
    {
        return $this->Works;
    }

    /**
     * Описание выполненных работ // ОписРабот
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AcceptanceCertificate552WorkDescription Works = 7;</code>
     * @param array<\Diadoc\Api\Proto\Invoicing\AcceptanceCertificate552WorkDescription>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWorks($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Invoicing\AcceptanceCertificate552WorkDescription::class);
        $this->Works = $arr;

        return $this;
    }

    /**
     * Дата составления документа о передаче товара // ИдентДок.ДатаДокПРУ
     *
     * Generated from protobuf field <code>string DocumentDate = 8;</code>
     * @return string
     */
    public function getDocumentDate()
    {
        return $this->DocumentDate;
    }

    /**
     * Дата составления документа о передаче товара // ИдентДок.ДатаДокПРУ
     *
     * Generated from protobuf field <code>string DocumentDate = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentDate = $var;

        return $this;
    }

    /**
     * Номер документа о передаче товара // ИдентДок.НомДокПРУ
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 9;</code>
     * @return string
     */
    public function getDocumentNumber()
    {
        return isset($this->DocumentNumber) ? $this->DocumentNumber : '';
    }

    public function hasDocumentNumber()
    {
        return isset($this->DocumentNumber);
    }

    public function clearDocumentNumber()
    {
        unset($this->DocumentNumber);
    }

    /**
     * Номер документа о передаче товара // ИдентДок.НомДокПРУ
     *
     * Generated from protobuf field <code>optional string DocumentNumber = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentNumber = $var;

        return $this;
    }

    /**
     * Дата исправления документа // ИспрДокПРУ.ДатаИспрДокПРУ
     *
     * Generated from protobuf field <code>optional string RevisionDate = 10;</code>
     * @return string
     */
    public function getRevisionDate()
    {
        return isset($this->RevisionDate) ? $this->RevisionDate : '';
    }

    public function hasRevisionDate()
    {
        return isset($this->RevisionDate);
    }

    public function clearRevisionDate()
    {
        unset($this->RevisionDate);
    }

    /**
     * Дата исправления документа // ИспрДокПРУ.ДатаИспрДокПРУ
     *
     * Generated from protobuf field <code>optional string RevisionDate = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setRevisionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->RevisionDate = $var;

        return $this;
    }

    /**
     * Номер исправления документа // ИспрДокПРУ.НомИспрДокПРУ
     *
     * Generated from protobuf field <code>optional string RevisionNumber = 11;</code>
     * @return string
     */
    public function getRevisionNumber()
    {
        return isset($this->RevisionNumber) ? $this->RevisionNumber : '';
    }

    public function hasRevisionNumber()
    {
        return isset($this->RevisionNumber);
    }

    public function clearRevisionNumber()
    {
        unset($this->RevisionNumber);
    }

    /**
     * Номер исправления документа // ИспрДокПРУ.НомИспрДокПРУ
     *
     * Generated from protobuf field <code>optional string RevisionNumber = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setRevisionNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->RevisionNumber = $var;

        return $this;
    }

    /**
     * Составитель файла информации продавца // НаимЭконСубСост
     *
     * Generated from protobuf field <code>string DocumentCreator = 12;</code>
     * @return string
     */
    public function getDocumentCreator()
    {
        return $this->DocumentCreator;
    }

    /**
     * Составитель файла информации продавца // НаимЭконСубСост
     *
     * Generated from protobuf field <code>string DocumentCreator = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentCreator($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentCreator = $var;

        return $this;
    }

    /**
     * Основание, по которому экономический субъект является составителем файла //ОснДоверОргСост
     *
     * Generated from protobuf field <code>optional string DocumentCreatorBase = 13;</code>
     * @return string
     */
    public function getDocumentCreatorBase()
    {
        return isset($this->DocumentCreatorBase) ? $this->DocumentCreatorBase : '';
    }

    public function hasDocumentCreatorBase()
    {
        return isset($this->DocumentCreatorBase);
    }

    public function clearDocumentCreatorBase()
    {
        unset($this->DocumentCreatorBase);
    }

    /**
     * Основание, по которому экономический субъект является составителем файла //ОснДоверОргСост
     *
     * Generated from protobuf field <code>optional string DocumentCreatorBase = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentCreatorBase($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentCreatorBase = $var;

        return $this;
    }

    /**
     * Вид операции // ВидОперации
     *
     * Generated from protobuf field <code>optional string OperationType = 14;</code>
     * @return string
     */
    public function getOperationType()
    {
        return isset($this->OperationType) ? $this->OperationType : '';
    }

    public function hasOperationType()
    {
        return isset($this->OperationType);
    }

    public function clearOperationType()
    {
        unset($this->OperationType);
    }

    /**
     * Вид операции // ВидОперации
     *
     * Generated from protobuf field <code>optional string OperationType = 14;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationType($var)
    {
        GPBUtil::checkString($var, True);
        $this->OperationType = $var;

        return $this;
    }

    /**
     * Заголовок содержания операции // ЗагСодОпер
     *
     * Generated from protobuf field <code>optional string OperationTitle = 15;</code>
     * @return string
     */
    public function getOperationTitle()
    {
        return isset($this->OperationTitle) ? $this->OperationTitle : '';
    }

    public function hasOperationTitle()
    {
        return isset($this->OperationTitle);
    }

    public function clearOperationTitle()
    {
        unset($this->OperationTitle);
    }

    /**
     * Заголовок содержания операции // ЗагСодОпер
     *
     * Generated from protobuf field <code>optional string OperationTitle = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationTitle($var)
    {
        GPBUtil::checkString($var, True);
        $this->OperationTitle = $var;

        return $this;
    }

    /**
     * Идентификатор государственного контракта // ИдГосКон
     *
     * Generated from protobuf field <code>optional string GovernmentContractInfo = 16;</code>
     * @return string
     */
    public function getGovernmentContractInfo()
    {
        return isset($this->GovernmentContractInfo) ? $this->GovernmentContractInfo : '';
    }

    public function hasGovernmentContractInfo()
    {
        return isset($this->GovernmentContractInfo);
    }

    public function clearGovernmentContractInfo()
    {
        unset($this->GovernmentContractInfo);
    }

    /**
     * Идентификатор государственного контракта // ИдГосКон
     *
     * Generated from protobuf field <code>optional string GovernmentContractInfo = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setGovernmentContractInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->GovernmentContractInfo = $var;

        return $this;
    }

    /**
     * Информационное поле документа // ИнфПолФХЖ1
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.AdditionalInfoId AdditionalInfoId = 17;</code>
     * @return \Diadoc\Api\Proto\Invoicing\AdditionalInfoId|null
     */
    public function getAdditionalInfoId()
    {
        return $this->AdditionalInfoId;
    }

    public function hasAdditionalInfoId()
    {
        return isset($this->AdditionalInfoId);
    }

    public function clearAdditionalInfoId()
    {
        unset($this->AdditionalInfoId);
    }

    /**
     * Информационное поле документа // ИнфПолФХЖ1
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.AdditionalInfoId AdditionalInfoId = 17;</code>
     * @param \Diadoc\Api\Proto\Invoicing\AdditionalInfoId $var
     * @return $this
     */
    public function setAdditionalInfoId($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\AdditionalInfoId::class);
        $this->AdditionalInfoId = $var;

        return $this;
    }

    /**
     * Наименование первичного документа, определенное организацией // НаимДок.НаимДокОпр
     *
     * Generated from protobuf field <code>string DocumentName = 18;</code>
     * @return string
     */
    public function getDocumentName()
    {
        return $this->DocumentName;
    }

    /**
     * Наименование первичного документа, определенное организацией // НаимДок.НаимДокОпр
     *
     * Generated from protobuf field <code>string DocumentName = 18;</code>
     * @param string $var
     * @return $this
     */
    public function setDocumentName($var)
    {
        GPBUtil::checkString($var, True);
        $this->DocumentName = $var;

        return $this;
    }

    /**
     * Содержание факта хозяйственной жизни - сведения о передаче результатов работ (о предъявлении оказанных услуг) // СодФХЖ2
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.AcceptanceCertificate552TransferInfo TransferInfo = 19;</code>
     * @return \Diadoc\Api\Proto\Invoicing\AcceptanceCertificate552TransferInfo|null
     */
    public function getTransferInfo()
    {
        return $this->TransferInfo;
    }

    public function hasTransferInfo()
    {
        return isset($this->TransferInfo);
    }

    public function clearTransferInfo()
    {
        unset($this->TransferInfo);
    }

    /**
     * Содержание факта хозяйственной жизни - сведения о передаче результатов работ (о предъявлении оказанных услуг) // СодФХЖ2
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.AcceptanceCertificate552TransferInfo TransferInfo = 19;</code>
     * @param \Diadoc\Api\Proto\Invoicing\AcceptanceCertificate552TransferInfo $var
     * @return $this
     */
    public function setTransferInfo($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\AcceptanceCertificate552TransferInfo::class);
        $this->TransferInfo = $var;

        return $this;
    }

}

