<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/InvoiceInfo.proto

namespace Diadoc\Api\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.InvoiceCorrectionInfo</code>
 */
class InvoiceCorrectionInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Дата СФ
     *
     * Generated from protobuf field <code>string InvoiceDate = 1;</code>
     */
    protected $InvoiceDate = '';
    /**
     * Номер СФ
     *
     * Generated from protobuf field <code>string InvoiceNumber = 2;</code>
     */
    protected $InvoiceNumber = '';
    /**
     * Дата ИСФ (заполняется, если КСФ/ИКСФ формируется на исправленный СФ)
     *
     * Generated from protobuf field <code>optional string InvoiceRevisionDate = 3;</code>
     */
    protected $InvoiceRevisionDate = null;
    /**
     * Номер ИСФ (заполняется, если КСФ/ИКСФ формируется на исправленный СФ)
     *
     * Generated from protobuf field <code>optional string InvoiceRevisionNumber = 4;</code>
     */
    protected $InvoiceRevisionNumber = null;
    /**
     * Дата КСФ
     *
     * Generated from protobuf field <code>string InvoiceCorrectionDate = 5;</code>
     */
    protected $InvoiceCorrectionDate = '';
    /**
     * Номер КСФ
     *
     * Generated from protobuf field <code>string InvoiceCorrectionNumber = 6;</code>
     */
    protected $InvoiceCorrectionNumber = '';
    /**
     * Дата ИКСФ (обязательно при формировании InvoiceCorrectionRevision)
     *
     * Generated from protobuf field <code>optional string InvoiceCorrectionRevisionDate = 7;</code>
     */
    protected $InvoiceCorrectionRevisionDate = null;
    /**
     * Номер ИКСФ (обязательно при формировании InvoiceCorrectionRevision)
     *
     * Generated from protobuf field <code>optional string InvoiceCorrectionRevisionNumber = 8;</code>
     */
    protected $InvoiceCorrectionRevisionNumber = null;
    /**
     * Продавец
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.DiadocOrganizationInfo Seller = 9;</code>
     */
    protected $Seller = null;
    /**
     * Покупатель
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.DiadocOrganizationInfo Buyer = 10;</code>
     */
    protected $Buyer = null;
    /**
     * Подписант
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Signer Signer = 11;</code>
     */
    protected $Signer = null;
    /**
     * Информация о товарах
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.InvoiceCorrectionItem Items = 12;</code>
     */
    private $Items;
    /**
     * Валюта (код)
     *
     * Generated from protobuf field <code>optional string Currency = 13;</code>
     */
    protected $Currency = null;
    /**
     * Суммы к увеличению
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsInc = 14;</code>
     */
    protected $TotalsInc = null;
    /**
     * Суммы к уменьшению
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsDec = 15;</code>
     */
    protected $TotalsDec = null;
    /**
     * Информационное поле документа v5.01
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 16;</code>
     */
    protected $AdditionalInfo = null;
    /**
     * Информационное поле документа v5.02
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AdditionalInfo AdditionalInfos = 17;</code>
     */
    private $AdditionalInfos;
    /**
     * Версия формата ФУФа (для тестирования систем в переходном периоде)
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceFormatVersion Version = 18;</code>
     */
    protected $Version = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $InvoiceDate
     *           Дата СФ
     *     @type string $InvoiceNumber
     *           Номер СФ
     *     @type string $InvoiceRevisionDate
     *           Дата ИСФ (заполняется, если КСФ/ИКСФ формируется на исправленный СФ)
     *     @type string $InvoiceRevisionNumber
     *           Номер ИСФ (заполняется, если КСФ/ИКСФ формируется на исправленный СФ)
     *     @type string $InvoiceCorrectionDate
     *           Дата КСФ
     *     @type string $InvoiceCorrectionNumber
     *           Номер КСФ
     *     @type string $InvoiceCorrectionRevisionDate
     *           Дата ИКСФ (обязательно при формировании InvoiceCorrectionRevision)
     *     @type string $InvoiceCorrectionRevisionNumber
     *           Номер ИКСФ (обязательно при формировании InvoiceCorrectionRevision)
     *     @type \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo $Seller
     *           Продавец
     *     @type \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo $Buyer
     *           Покупатель
     *     @type \Diadoc\Api\Proto\Invoicing\Signer $Signer
     *           Подписант
     *     @type array<\Diadoc\Api\Proto\Invoicing\InvoiceCorrectionItem>|\Google\Protobuf\Internal\RepeatedField $Items
     *           Информация о товарах
     *     @type string $Currency
     *           Валюта (код)
     *     @type \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff $TotalsInc
     *           Суммы к увеличению
     *     @type \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff $TotalsDec
     *           Суммы к уменьшению
     *     @type string $AdditionalInfo
     *           Информационное поле документа v5.01
     *     @type array<\Diadoc\Api\Proto\Invoicing\AdditionalInfo>|\Google\Protobuf\Internal\RepeatedField $AdditionalInfos
     *           Информационное поле документа v5.02
     *     @type int $Version
     *           Версия формата ФУФа (для тестирования систем в переходном периоде)
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\InvoiceInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Дата СФ
     *
     * Generated from protobuf field <code>string InvoiceDate = 1;</code>
     * @return string
     */
    public function getInvoiceDate()
    {
        return $this->InvoiceDate;
    }

    /**
     * Дата СФ
     *
     * Generated from protobuf field <code>string InvoiceDate = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->InvoiceDate = $var;

        return $this;
    }

    /**
     * Номер СФ
     *
     * Generated from protobuf field <code>string InvoiceNumber = 2;</code>
     * @return string
     */
    public function getInvoiceNumber()
    {
        return $this->InvoiceNumber;
    }

    /**
     * Номер СФ
     *
     * Generated from protobuf field <code>string InvoiceNumber = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->InvoiceNumber = $var;

        return $this;
    }

    /**
     * Дата ИСФ (заполняется, если КСФ/ИКСФ формируется на исправленный СФ)
     *
     * Generated from protobuf field <code>optional string InvoiceRevisionDate = 3;</code>
     * @return string
     */
    public function getInvoiceRevisionDate()
    {
        return isset($this->InvoiceRevisionDate) ? $this->InvoiceRevisionDate : '';
    }

    public function hasInvoiceRevisionDate()
    {
        return isset($this->InvoiceRevisionDate);
    }

    public function clearInvoiceRevisionDate()
    {
        unset($this->InvoiceRevisionDate);
    }

    /**
     * Дата ИСФ (заполняется, если КСФ/ИКСФ формируется на исправленный СФ)
     *
     * Generated from protobuf field <code>optional string InvoiceRevisionDate = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceRevisionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->InvoiceRevisionDate = $var;

        return $this;
    }

    /**
     * Номер ИСФ (заполняется, если КСФ/ИКСФ формируется на исправленный СФ)
     *
     * Generated from protobuf field <code>optional string InvoiceRevisionNumber = 4;</code>
     * @return string
     */
    public function getInvoiceRevisionNumber()
    {
        return isset($this->InvoiceRevisionNumber) ? $this->InvoiceRevisionNumber : '';
    }

    public function hasInvoiceRevisionNumber()
    {
        return isset($this->InvoiceRevisionNumber);
    }

    public function clearInvoiceRevisionNumber()
    {
        unset($this->InvoiceRevisionNumber);
    }

    /**
     * Номер ИСФ (заполняется, если КСФ/ИКСФ формируется на исправленный СФ)
     *
     * Generated from protobuf field <code>optional string InvoiceRevisionNumber = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceRevisionNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->InvoiceRevisionNumber = $var;

        return $this;
    }

    /**
     * Дата КСФ
     *
     * Generated from protobuf field <code>string InvoiceCorrectionDate = 5;</code>
     * @return string
     */
    public function getInvoiceCorrectionDate()
    {
        return $this->InvoiceCorrectionDate;
    }

    /**
     * Дата КСФ
     *
     * Generated from protobuf field <code>string InvoiceCorrectionDate = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceCorrectionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->InvoiceCorrectionDate = $var;

        return $this;
    }

    /**
     * Номер КСФ
     *
     * Generated from protobuf field <code>string InvoiceCorrectionNumber = 6;</code>
     * @return string
     */
    public function getInvoiceCorrectionNumber()
    {
        return $this->InvoiceCorrectionNumber;
    }

    /**
     * Номер КСФ
     *
     * Generated from protobuf field <code>string InvoiceCorrectionNumber = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceCorrectionNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->InvoiceCorrectionNumber = $var;

        return $this;
    }

    /**
     * Дата ИКСФ (обязательно при формировании InvoiceCorrectionRevision)
     *
     * Generated from protobuf field <code>optional string InvoiceCorrectionRevisionDate = 7;</code>
     * @return string
     */
    public function getInvoiceCorrectionRevisionDate()
    {
        return isset($this->InvoiceCorrectionRevisionDate) ? $this->InvoiceCorrectionRevisionDate : '';
    }

    public function hasInvoiceCorrectionRevisionDate()
    {
        return isset($this->InvoiceCorrectionRevisionDate);
    }

    public function clearInvoiceCorrectionRevisionDate()
    {
        unset($this->InvoiceCorrectionRevisionDate);
    }

    /**
     * Дата ИКСФ (обязательно при формировании InvoiceCorrectionRevision)
     *
     * Generated from protobuf field <code>optional string InvoiceCorrectionRevisionDate = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceCorrectionRevisionDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->InvoiceCorrectionRevisionDate = $var;

        return $this;
    }

    /**
     * Номер ИКСФ (обязательно при формировании InvoiceCorrectionRevision)
     *
     * Generated from protobuf field <code>optional string InvoiceCorrectionRevisionNumber = 8;</code>
     * @return string
     */
    public function getInvoiceCorrectionRevisionNumber()
    {
        return isset($this->InvoiceCorrectionRevisionNumber) ? $this->InvoiceCorrectionRevisionNumber : '';
    }

    public function hasInvoiceCorrectionRevisionNumber()
    {
        return isset($this->InvoiceCorrectionRevisionNumber);
    }

    public function clearInvoiceCorrectionRevisionNumber()
    {
        unset($this->InvoiceCorrectionRevisionNumber);
    }

    /**
     * Номер ИКСФ (обязательно при формировании InvoiceCorrectionRevision)
     *
     * Generated from protobuf field <code>optional string InvoiceCorrectionRevisionNumber = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setInvoiceCorrectionRevisionNumber($var)
    {
        GPBUtil::checkString($var, True);
        $this->InvoiceCorrectionRevisionNumber = $var;

        return $this;
    }

    /**
     * Продавец
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.DiadocOrganizationInfo Seller = 9;</code>
     * @return \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo|null
     */
    public function getSeller()
    {
        return $this->Seller;
    }

    public function hasSeller()
    {
        return isset($this->Seller);
    }

    public function clearSeller()
    {
        unset($this->Seller);
    }

    /**
     * Продавец
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.DiadocOrganizationInfo Seller = 9;</code>
     * @param \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo $var
     * @return $this
     */
    public function setSeller($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo::class);
        $this->Seller = $var;

        return $this;
    }

    /**
     * Покупатель
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.DiadocOrganizationInfo Buyer = 10;</code>
     * @return \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo|null
     */
    public function getBuyer()
    {
        return $this->Buyer;
    }

    public function hasBuyer()
    {
        return isset($this->Buyer);
    }

    public function clearBuyer()
    {
        unset($this->Buyer);
    }

    /**
     * Покупатель
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.DiadocOrganizationInfo Buyer = 10;</code>
     * @param \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo $var
     * @return $this
     */
    public function setBuyer($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\DiadocOrganizationInfo::class);
        $this->Buyer = $var;

        return $this;
    }

    /**
     * Подписант
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Signer Signer = 11;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Signer|null
     */
    public function getSigner()
    {
        return $this->Signer;
    }

    public function hasSigner()
    {
        return isset($this->Signer);
    }

    public function clearSigner()
    {
        unset($this->Signer);
    }

    /**
     * Подписант
     *
     * Generated from protobuf field <code>.Diadoc.Api.Proto.Invoicing.Signer Signer = 11;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Signer $var
     * @return $this
     */
    public function setSigner($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Signer::class);
        $this->Signer = $var;

        return $this;
    }

    /**
     * Информация о товарах
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.InvoiceCorrectionItem Items = 12;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->Items;
    }

    /**
     * Информация о товарах
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.InvoiceCorrectionItem Items = 12;</code>
     * @param array<\Diadoc\Api\Proto\Invoicing\InvoiceCorrectionItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Invoicing\InvoiceCorrectionItem::class);
        $this->Items = $arr;

        return $this;
    }

    /**
     * Валюта (код)
     *
     * Generated from protobuf field <code>optional string Currency = 13;</code>
     * @return string
     */
    public function getCurrency()
    {
        return isset($this->Currency) ? $this->Currency : '';
    }

    public function hasCurrency()
    {
        return isset($this->Currency);
    }

    public function clearCurrency()
    {
        unset($this->Currency);
    }

    /**
     * Валюта (код)
     *
     * Generated from protobuf field <code>optional string Currency = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setCurrency($var)
    {
        GPBUtil::checkString($var, True);
        $this->Currency = $var;

        return $this;
    }

    /**
     * Суммы к увеличению
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsInc = 14;</code>
     * @return \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff|null
     */
    public function getTotalsInc()
    {
        return $this->TotalsInc;
    }

    public function hasTotalsInc()
    {
        return isset($this->TotalsInc);
    }

    public function clearTotalsInc()
    {
        unset($this->TotalsInc);
    }

    /**
     * Суммы к увеличению
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsInc = 14;</code>
     * @param \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff $var
     * @return $this
     */
    public function setTotalsInc($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff::class);
        $this->TotalsInc = $var;

        return $this;
    }

    /**
     * Суммы к уменьшению
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsDec = 15;</code>
     * @return \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff|null
     */
    public function getTotalsDec()
    {
        return $this->TotalsDec;
    }

    public function hasTotalsDec()
    {
        return isset($this->TotalsDec);
    }

    public function clearTotalsDec()
    {
        unset($this->TotalsDec);
    }

    /**
     * Суммы к уменьшению
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsDec = 15;</code>
     * @param \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff $var
     * @return $this
     */
    public function setTotalsDec($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff::class);
        $this->TotalsDec = $var;

        return $this;
    }

    /**
     * Информационное поле документа v5.01
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 16;</code>
     * @return string
     */
    public function getAdditionalInfo()
    {
        return isset($this->AdditionalInfo) ? $this->AdditionalInfo : '';
    }

    public function hasAdditionalInfo()
    {
        return isset($this->AdditionalInfo);
    }

    public function clearAdditionalInfo()
    {
        unset($this->AdditionalInfo);
    }

    /**
     * Информационное поле документа v5.01
     *
     * Generated from protobuf field <code>optional string AdditionalInfo = 16;</code>
     * @param string $var
     * @return $this
     */
    public function setAdditionalInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->AdditionalInfo = $var;

        return $this;
    }

    /**
     * Информационное поле документа v5.02
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AdditionalInfo AdditionalInfos = 17;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdditionalInfos()
    {
        return $this->AdditionalInfos;
    }

    /**
     * Информационное поле документа v5.02
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AdditionalInfo AdditionalInfos = 17;</code>
     * @param array<\Diadoc\Api\Proto\Invoicing\AdditionalInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdditionalInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Invoicing\AdditionalInfo::class);
        $this->AdditionalInfos = $arr;

        return $this;
    }

    /**
     * Версия формата ФУФа (для тестирования систем в переходном периоде)
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceFormatVersion Version = 18;</code>
     * @return int
     */
    public function getVersion()
    {
        return isset($this->Version) ? $this->Version : 0;
    }

    public function hasVersion()
    {
        return isset($this->Version);
    }

    public function clearVersion()
    {
        unset($this->Version);
    }

    /**
     * Версия формата ФУФа (для тестирования систем в переходном периоде)
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceFormatVersion Version = 18;</code>
     * @param int $var
     * @return $this
     */
    public function setVersion($var)
    {
        GPBUtil::checkEnum($var, \Diadoc\Api\Proto\Invoicing\InvoiceFormatVersion::class);
        $this->Version = $var;

        return $this;
    }

}

