<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/UniversalTransferDocumentInfo.proto

namespace Diadoc\Api\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.InvoiceCorrectionTable</code>
 */
class InvoiceCorrectionTable extends \Google\Protobuf\Internal\Message
{
    /**
     * Информация о товарах // СведТов
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.ExtendedInvoiceCorrectionItem Items = 1;</code>
     */
    private $Items;
    /**
     * Суммы к увеличению // ВсегоУвел
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsInc = 2;</code>
     */
    protected $TotalsInc = null;
    /**
     * Суммы к уменьшению // ВсегоУм
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsDec = 3;</code>
     */
    protected $TotalsDec = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Diadoc\Api\Proto\Invoicing\ExtendedInvoiceCorrectionItem>|\Google\Protobuf\Internal\RepeatedField $Items
     *           Информация о товарах // СведТов
     *     @type \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff $TotalsInc
     *           Суммы к увеличению // ВсегоУвел
     *     @type \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff $TotalsDec
     *           Суммы к уменьшению // ВсегоУм
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\UniversalTransferDocumentInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Информация о товарах // СведТов
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.ExtendedInvoiceCorrectionItem Items = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getItems()
    {
        return $this->Items;
    }

    /**
     * Информация о товарах // СведТов
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.ExtendedInvoiceCorrectionItem Items = 1;</code>
     * @param array<\Diadoc\Api\Proto\Invoicing\ExtendedInvoiceCorrectionItem>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setItems($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Invoicing\ExtendedInvoiceCorrectionItem::class);
        $this->Items = $arr;

        return $this;
    }

    /**
     * Суммы к увеличению // ВсегоУвел
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsInc = 2;</code>
     * @return \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff|null
     */
    public function getTotalsInc()
    {
        return $this->TotalsInc;
    }

    public function hasTotalsInc()
    {
        return isset($this->TotalsInc);
    }

    public function clearTotalsInc()
    {
        unset($this->TotalsInc);
    }

    /**
     * Суммы к увеличению // ВсегоУвел
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsInc = 2;</code>
     * @param \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff $var
     * @return $this
     */
    public function setTotalsInc($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff::class);
        $this->TotalsInc = $var;

        return $this;
    }

    /**
     * Суммы к уменьшению // ВсегоУм
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsDec = 3;</code>
     * @return \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff|null
     */
    public function getTotalsDec()
    {
        return $this->TotalsDec;
    }

    public function hasTotalsDec()
    {
        return isset($this->TotalsDec);
    }

    public function clearTotalsDec()
    {
        unset($this->TotalsDec);
    }

    /**
     * Суммы к уменьшению // ВсегоУм
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.InvoiceTotalsDiff TotalsDec = 3;</code>
     * @param \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff $var
     * @return $this
     */
    public function setTotalsDec($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\InvoiceTotalsDiff::class);
        $this->TotalsDec = $var;

        return $this;
    }

}

