<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/UniversalTransferDocumentInfo.proto

namespace Diadoc\Api\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.OtherIssuer</code>
 */
class OtherIssuer extends \Google\Protobuf\Internal\Message
{
    /**
     * Должность предстваителя организации // Должность
     *
     * Generated from protobuf field <code>optional string TransferEmployeePosition = 1;</code>
     */
    protected $TransferEmployeePosition = null;
    /**
     * Иные сведения, идентифицирующие физическое лицо // ИныеСвед
     *
     * Generated from protobuf field <code>optional string TransferEmployeeInfo = 2;</code>
     */
    protected $TransferEmployeeInfo = null;
    /**
     * Наименование организации, которой доверена передача // НаимОргПер
     *
     * Generated from protobuf field <code>optional string TransferOrganizationName = 3;</code>
     */
    protected $TransferOrganizationName = null;
    /**
     * Основание, по которому организации доверена передача // ОснДоверОргПер
     *
     * Generated from protobuf field <code>optional string TransferOrganizationBase = 4;</code>
     */
    protected $TransferOrganizationBase = null;
    /**
     * Основание полномочий предстваителя // ОснПолнПредПер (ОснДоверФЛ)
     *
     * Generated from protobuf field <code>optional string TransferEmployeeBase = 5;</code>
     */
    protected $TransferEmployeeBase = null;
    /**
     * Фамилия // Фамилия
     *
     * Generated from protobuf field <code>string TransferSurname = 6;</code>
     */
    protected $TransferSurname = '';
    /**
     * Имя // Имя
     *
     * Generated from protobuf field <code>string TransferFirstName = 7;</code>
     */
    protected $TransferFirstName = '';
    /**
     * Отчество // Отчество
     *
     * Generated from protobuf field <code>optional string TransferPatronymic = 8;</code>
     */
    protected $TransferPatronymic = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $TransferEmployeePosition
     *           Должность предстваителя организации // Должность
     *     @type string $TransferEmployeeInfo
     *           Иные сведения, идентифицирующие физическое лицо // ИныеСвед
     *     @type string $TransferOrganizationName
     *           Наименование организации, которой доверена передача // НаимОргПер
     *     @type string $TransferOrganizationBase
     *           Основание, по которому организации доверена передача // ОснДоверОргПер
     *     @type string $TransferEmployeeBase
     *           Основание полномочий предстваителя // ОснПолнПредПер (ОснДоверФЛ)
     *     @type string $TransferSurname
     *           Фамилия // Фамилия
     *     @type string $TransferFirstName
     *           Имя // Имя
     *     @type string $TransferPatronymic
     *           Отчество // Отчество
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\UniversalTransferDocumentInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Должность предстваителя организации // Должность
     *
     * Generated from protobuf field <code>optional string TransferEmployeePosition = 1;</code>
     * @return string
     */
    public function getTransferEmployeePosition()
    {
        return isset($this->TransferEmployeePosition) ? $this->TransferEmployeePosition : '';
    }

    public function hasTransferEmployeePosition()
    {
        return isset($this->TransferEmployeePosition);
    }

    public function clearTransferEmployeePosition()
    {
        unset($this->TransferEmployeePosition);
    }

    /**
     * Должность предстваителя организации // Должность
     *
     * Generated from protobuf field <code>optional string TransferEmployeePosition = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setTransferEmployeePosition($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransferEmployeePosition = $var;

        return $this;
    }

    /**
     * Иные сведения, идентифицирующие физическое лицо // ИныеСвед
     *
     * Generated from protobuf field <code>optional string TransferEmployeeInfo = 2;</code>
     * @return string
     */
    public function getTransferEmployeeInfo()
    {
        return isset($this->TransferEmployeeInfo) ? $this->TransferEmployeeInfo : '';
    }

    public function hasTransferEmployeeInfo()
    {
        return isset($this->TransferEmployeeInfo);
    }

    public function clearTransferEmployeeInfo()
    {
        unset($this->TransferEmployeeInfo);
    }

    /**
     * Иные сведения, идентифицирующие физическое лицо // ИныеСвед
     *
     * Generated from protobuf field <code>optional string TransferEmployeeInfo = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTransferEmployeeInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransferEmployeeInfo = $var;

        return $this;
    }

    /**
     * Наименование организации, которой доверена передача // НаимОргПер
     *
     * Generated from protobuf field <code>optional string TransferOrganizationName = 3;</code>
     * @return string
     */
    public function getTransferOrganizationName()
    {
        return isset($this->TransferOrganizationName) ? $this->TransferOrganizationName : '';
    }

    public function hasTransferOrganizationName()
    {
        return isset($this->TransferOrganizationName);
    }

    public function clearTransferOrganizationName()
    {
        unset($this->TransferOrganizationName);
    }

    /**
     * Наименование организации, которой доверена передача // НаимОргПер
     *
     * Generated from protobuf field <code>optional string TransferOrganizationName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTransferOrganizationName($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransferOrganizationName = $var;

        return $this;
    }

    /**
     * Основание, по которому организации доверена передача // ОснДоверОргПер
     *
     * Generated from protobuf field <code>optional string TransferOrganizationBase = 4;</code>
     * @return string
     */
    public function getTransferOrganizationBase()
    {
        return isset($this->TransferOrganizationBase) ? $this->TransferOrganizationBase : '';
    }

    public function hasTransferOrganizationBase()
    {
        return isset($this->TransferOrganizationBase);
    }

    public function clearTransferOrganizationBase()
    {
        unset($this->TransferOrganizationBase);
    }

    /**
     * Основание, по которому организации доверена передача // ОснДоверОргПер
     *
     * Generated from protobuf field <code>optional string TransferOrganizationBase = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTransferOrganizationBase($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransferOrganizationBase = $var;

        return $this;
    }

    /**
     * Основание полномочий предстваителя // ОснПолнПредПер (ОснДоверФЛ)
     *
     * Generated from protobuf field <code>optional string TransferEmployeeBase = 5;</code>
     * @return string
     */
    public function getTransferEmployeeBase()
    {
        return isset($this->TransferEmployeeBase) ? $this->TransferEmployeeBase : '';
    }

    public function hasTransferEmployeeBase()
    {
        return isset($this->TransferEmployeeBase);
    }

    public function clearTransferEmployeeBase()
    {
        unset($this->TransferEmployeeBase);
    }

    /**
     * Основание полномочий предстваителя // ОснПолнПредПер (ОснДоверФЛ)
     *
     * Generated from protobuf field <code>optional string TransferEmployeeBase = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setTransferEmployeeBase($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransferEmployeeBase = $var;

        return $this;
    }

    /**
     * Фамилия // Фамилия
     *
     * Generated from protobuf field <code>string TransferSurname = 6;</code>
     * @return string
     */
    public function getTransferSurname()
    {
        return $this->TransferSurname;
    }

    /**
     * Фамилия // Фамилия
     *
     * Generated from protobuf field <code>string TransferSurname = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setTransferSurname($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransferSurname = $var;

        return $this;
    }

    /**
     * Имя // Имя
     *
     * Generated from protobuf field <code>string TransferFirstName = 7;</code>
     * @return string
     */
    public function getTransferFirstName()
    {
        return $this->TransferFirstName;
    }

    /**
     * Имя // Имя
     *
     * Generated from protobuf field <code>string TransferFirstName = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setTransferFirstName($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransferFirstName = $var;

        return $this;
    }

    /**
     * Отчество // Отчество
     *
     * Generated from protobuf field <code>optional string TransferPatronymic = 8;</code>
     * @return string
     */
    public function getTransferPatronymic()
    {
        return isset($this->TransferPatronymic) ? $this->TransferPatronymic : '';
    }

    public function hasTransferPatronymic()
    {
        return isset($this->TransferPatronymic);
    }

    public function clearTransferPatronymic()
    {
        unset($this->TransferPatronymic);
    }

    /**
     * Отчество // Отчество
     *
     * Generated from protobuf field <code>optional string TransferPatronymic = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setTransferPatronymic($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransferPatronymic = $var;

        return $this;
    }

}

