<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Invoicing/TovTorgInfo.proto

namespace Diadoc\Api\Proto\Invoicing;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Invoicing.TovTorgTransferInfo</code>
 */
class TovTorgTransferInfo extends \Google\Protobuf\Internal\Message
{
    /**
     * Содержание операции // СодОпер
     *
     * Generated from protobuf field <code>string OperationInfo = 1;</code>
     */
    protected $OperationInfo = '';
    /**
     * Дата отгрузки // ДатаОтпуск
     *
     * Generated from protobuf field <code>optional string TransferDate = 2;</code>
     */
    protected $TransferDate = null;
    /**
     * Приложение, сертификаты и прочее // КолПрил
     *
     * Generated from protobuf field <code>optional string Attachment = 3;</code>
     */
    protected $Attachment = null;
    /**
     * Транспортная накладная //ТранНакл
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.Waybill Waybills = 4;</code>
     */
    private $Waybills;
    /**
     * Работник организации продавца // СвЛицОтпГруз.РабОргПрод
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Employee Employee = 5;</code>
     */
    protected $Employee = null;
    /**
     * Иное лицо // СвЛицОтпГруз.ИнЛицо
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OtherIssuer OtherIssuer = 6;</code>
     */
    protected $OtherIssuer = null;
    /**
     * Информационное поле документа // ИнфПолФХЖ3
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AdditionalInfo AdditionalInfos = 7;</code>
     */
    private $AdditionalInfos;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $OperationInfo
     *           Содержание операции // СодОпер
     *     @type string $TransferDate
     *           Дата отгрузки // ДатаОтпуск
     *     @type string $Attachment
     *           Приложение, сертификаты и прочее // КолПрил
     *     @type array<\Diadoc\Api\Proto\Invoicing\Waybill>|\Google\Protobuf\Internal\RepeatedField $Waybills
     *           Транспортная накладная //ТранНакл
     *     @type \Diadoc\Api\Proto\Invoicing\Employee $Employee
     *           Работник организации продавца // СвЛицОтпГруз.РабОргПрод
     *     @type \Diadoc\Api\Proto\Invoicing\OtherIssuer $OtherIssuer
     *           Иное лицо // СвЛицОтпГруз.ИнЛицо
     *     @type array<\Diadoc\Api\Proto\Invoicing\AdditionalInfo>|\Google\Protobuf\Internal\RepeatedField $AdditionalInfos
     *           Информационное поле документа // ИнфПолФХЖ3
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Invoicing\TovTorgInfo::initOnce();
        parent::__construct($data);
    }

    /**
     * Содержание операции // СодОпер
     *
     * Generated from protobuf field <code>string OperationInfo = 1;</code>
     * @return string
     */
    public function getOperationInfo()
    {
        return $this->OperationInfo;
    }

    /**
     * Содержание операции // СодОпер
     *
     * Generated from protobuf field <code>string OperationInfo = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->OperationInfo = $var;

        return $this;
    }

    /**
     * Дата отгрузки // ДатаОтпуск
     *
     * Generated from protobuf field <code>optional string TransferDate = 2;</code>
     * @return string
     */
    public function getTransferDate()
    {
        return isset($this->TransferDate) ? $this->TransferDate : '';
    }

    public function hasTransferDate()
    {
        return isset($this->TransferDate);
    }

    public function clearTransferDate()
    {
        unset($this->TransferDate);
    }

    /**
     * Дата отгрузки // ДатаОтпуск
     *
     * Generated from protobuf field <code>optional string TransferDate = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTransferDate($var)
    {
        GPBUtil::checkString($var, True);
        $this->TransferDate = $var;

        return $this;
    }

    /**
     * Приложение, сертификаты и прочее // КолПрил
     *
     * Generated from protobuf field <code>optional string Attachment = 3;</code>
     * @return string
     */
    public function getAttachment()
    {
        return isset($this->Attachment) ? $this->Attachment : '';
    }

    public function hasAttachment()
    {
        return isset($this->Attachment);
    }

    public function clearAttachment()
    {
        unset($this->Attachment);
    }

    /**
     * Приложение, сертификаты и прочее // КолПрил
     *
     * Generated from protobuf field <code>optional string Attachment = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAttachment($var)
    {
        GPBUtil::checkString($var, True);
        $this->Attachment = $var;

        return $this;
    }

    /**
     * Транспортная накладная //ТранНакл
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.Waybill Waybills = 4;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getWaybills()
    {
        return $this->Waybills;
    }

    /**
     * Транспортная накладная //ТранНакл
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.Waybill Waybills = 4;</code>
     * @param array<\Diadoc\Api\Proto\Invoicing\Waybill>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setWaybills($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Invoicing\Waybill::class);
        $this->Waybills = $arr;

        return $this;
    }

    /**
     * Работник организации продавца // СвЛицОтпГруз.РабОргПрод
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Employee Employee = 5;</code>
     * @return \Diadoc\Api\Proto\Invoicing\Employee|null
     */
    public function getEmployee()
    {
        return $this->Employee;
    }

    public function hasEmployee()
    {
        return isset($this->Employee);
    }

    public function clearEmployee()
    {
        unset($this->Employee);
    }

    /**
     * Работник организации продавца // СвЛицОтпГруз.РабОргПрод
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.Employee Employee = 5;</code>
     * @param \Diadoc\Api\Proto\Invoicing\Employee $var
     * @return $this
     */
    public function setEmployee($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\Employee::class);
        $this->Employee = $var;

        return $this;
    }

    /**
     * Иное лицо // СвЛицОтпГруз.ИнЛицо
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OtherIssuer OtherIssuer = 6;</code>
     * @return \Diadoc\Api\Proto\Invoicing\OtherIssuer|null
     */
    public function getOtherIssuer()
    {
        return $this->OtherIssuer;
    }

    public function hasOtherIssuer()
    {
        return isset($this->OtherIssuer);
    }

    public function clearOtherIssuer()
    {
        unset($this->OtherIssuer);
    }

    /**
     * Иное лицо // СвЛицОтпГруз.ИнЛицо
     *
     * Generated from protobuf field <code>optional .Diadoc.Api.Proto.Invoicing.OtherIssuer OtherIssuer = 6;</code>
     * @param \Diadoc\Api\Proto\Invoicing\OtherIssuer $var
     * @return $this
     */
    public function setOtherIssuer($var)
    {
        GPBUtil::checkMessage($var, \Diadoc\Api\Proto\Invoicing\OtherIssuer::class);
        $this->OtherIssuer = $var;

        return $this;
    }

    /**
     * Информационное поле документа // ИнфПолФХЖ3
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AdditionalInfo AdditionalInfos = 7;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getAdditionalInfos()
    {
        return $this->AdditionalInfos;
    }

    /**
     * Информационное поле документа // ИнфПолФХЖ3
     *
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Invoicing.AdditionalInfo AdditionalInfos = 7;</code>
     * @param array<\Diadoc\Api\Proto\Invoicing\AdditionalInfo>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setAdditionalInfos($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Invoicing\AdditionalInfo::class);
        $this->AdditionalInfos = $arr;

        return $this;
    }

}

