<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Certificates/CertificateList.proto

namespace Diadoc\Api\Proto\Certificates;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>Diadoc.Api.Proto.Certificates.CertificateList</code>
 */
class CertificateList extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Certificates.CertificateInfoV2 Certificates = 1;</code>
     */
    private $Certificates;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array<\Diadoc\Api\Proto\Certificates\CertificateInfoV2>|\Google\Protobuf\Internal\RepeatedField $Certificates
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Certificates\CertificateList::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Certificates.CertificateInfoV2 Certificates = 1;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getCertificates()
    {
        return $this->Certificates;
    }

    /**
     * Generated from protobuf field <code>repeated .Diadoc.Api.Proto.Certificates.CertificateInfoV2 Certificates = 1;</code>
     * @param array<\Diadoc\Api\Proto\Certificates\CertificateInfoV2>|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setCertificates($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Diadoc\Api\Proto\Certificates\CertificateInfoV2::class);
        $this->Certificates = $arr;

        return $this;
    }

}

